[[Basic_Configuration]]
= Basic Configuration
:toc:

The default configuration installs Zimbra-LDAP, Zimbra-MTA with
anti-virus and anti-spam protection, the Zimbra mailbox server, SNMP
monitoring tools (optional), Zimbra-spell (optional), the logger tool
(optional), and the Zimbra proxy (optional) on one server.

The menu driven installation displays the components and their existing
default values. You can modify the information during the installation
process. The table below describes the menu options.

*Main Menu Options*

[cols=",a",options="header",]
|========================
|*Main Menu* |*Description*

2+|*Common Configuration - These are common settings for all servers*

|Hostname
|The host name configured in the operating system installation

|LDAP master host
|The LDAP host name. On a single server installation, this name is the
same as the hostname.

|LDAP port
|The default port is 389

|LDAP Admin password
|This is the master LDAP password.

|Secure interprocess communications
|The default is YES. Secure interprocess communications requires that
connections between the mail store, and other processes that use Java,
use secure communications. It also specifies whether secure
communications should be used between the master LDAP server and the
replica LDAP servers for replication.

|Time Zone
|Select the time zone to apply to the default COS. The time zone that
should be entered is the time zone that the majority of users in the COS
will be located in. The default time zone is PST (Pacific Time).

|IP Mode
|IPv4 or IPv6.

2+|*zimbra-ldap*

|Status
|The default is *Enabled*.  For replica LDAP servers, the status can be
changed to Disabled if the database is manually loaded after
installation completes.

|Create Domain
|You can create one domain during installation. Additional domains can be
created from the administration console.

|Domain to create
|The default domain is the fully qualified hostname of the server. If you
created a valid mail domain on your DNS server, enter it now. In most
cases, you will accept the default.

|LDAP Root password
|The root LDAP password for internal LDAP operations.

|LDAP Replication password
|This is the password used by the LDAP replication user to identify
itself to the LDAP master and must be the same as the password on the
LDAP master server.

|LDAP Postfix password
|This is the password used by the postfix user to identify itself to the
LDAP server and must be configured on the MTA server to be the same as
the password on the LDAP master server.

|LDAP Amavis password
|This is the password used by the amavis user to identify itself to the
LDAP server and must be configured on the MTA server to be the same as
the password on the LDAP server.

|*zimbra-logger*
|When installed, it is automatically enabled. Logs from the hosts are
sent to the mailbox server where zimbra-logger is installed.  The
information is used for generating statistics graphs and for message
tracing.

2+|*zimbra-mta*

|*MTA Auth host*
|This is configured automatically if the MTA authentication server host
is on the same server, but must be configured if the authentication
server is not on the MTA.

|*Enable Spamassassin* | Default is enabled.

|*Enable ClamAV* | Default is enabled.

|*Notification address for AV alerts* 
a|Sets the notification address for AV alerts.
You can either accept the default or create a new address.
If you create a new address, remember to provision this address
from the admin console. + 
**Note:** If the virus notification address does not exist and your
host name is the same as the domain name on the Zimbra server,
the virus notifications queue in the Zimbra MTA server cannot be delivered.

|**Bind password for Postfix LDAP user**
|Automatically set.  This is the password used by the postfix user to
identify itself to the LDAP server and must be configured on the MTA
server to be the same as the password on the LDAP master server.

|**Bind password for Amavis LDAP user**
|Automatically set. This is the password used by the amavis user to
identify itself to the LDAP server and must be configured on the MTA
server to be the same as the password on the LDAP server.

2+|*zimbra-dnscache (optional)*

|**Master DNS IP address(es)** | IP addresses of DNS servers

|**Enable DNS lookups over TCP** | Yes or No

|*Enable DNS lookups over UDP* | Yes or No

|*Only allow TCP to communicate with Master DNS* | Yes or No

2+|*zimbra-snmp(optional)*

|*Enable SNMP notifications* | The default is Yes.

|*SNMP Trap hostname* | The hostname of the SNMP Trap destination

|*Enable SMTP notification* | The default is Yes.

|*SMTP Source email address* | From address to use in email notifications

|*SMTP Destination email address* | To address to use in email notifications

2+|*zimbra-store*

|Create Admin User
a|*Yes* or *No*. The administrator account is created during installation.
This account is the first account provisioned on the Zimbra server and
allows you to log on to the administration console.

a|Admin user to create
|The user name assigned to the administrator account. Once the
administrator account has been created, it is suggested that you *do not
rename the account* as automatic {product-name} notifications might
not be received.

|Admin Password
|You must set the admin account password. The password is case sensitive
and must be a *minimum of six characters*. The administrator name, mail
address, and password are required to log in to the administration
console.

|Anti-virus quarantine user
|A virus quarantine account is automatically created during installation.
When AmavisD identifies an email message with a virus, the email is
automatically sent to this mailbox. The virus quarantine mailbox is
configured to delete messages older than 7 days.

|Enable automated spam training
a| *Yes* or *No*.  By default, the automated spam training filter is
enabled and two mail accounts are created - one for the 
*Spam Training User* and one for the *Non-spam (HAM) Training User*.
See the next 2 menu items which will be shown if spam training is
enabled. + 
These addresses are automatically configured
to work with the spam training filter. The accounts created have
randomly selected names. To recognize what the accounts are used for,
you may want to change their names.

|*Spam Training User*
| to receive mail notification about mail that was not marked as junk,
but should have been.

|*Non-spam (HAM) Training User*
| to receive mail notification about mail that was marked as junk,
but should not have been.

2+|The default port configurations are shown

| *SMTP host* | Defaults to current server name

| *Web server HTTP port:* | default *80*

| *Web server HTTPS port:* | default *443*

| *Web server mode*
a|Can be *HTTP*, *HTTPS*, *Mixed*, *Both* or *Redirect*.

** *Mixed* mode uses HTTPS for logging in and HTTP for normal session
traffic
** *Both* mode means that an HTTP session stays HTTP, including during
the login phase, and an HTTPS session remains HTTPS throughout,
including the login phase.
** *Redirect* mode redirects any users connecting via HTTP to an HTTPS
connection.
** All modes use SSL encryption for back-end administrative traffic.

| **IMAP server port** | default *143*
| **IMAP server SSL port** | default *993*
| **POP server port** | default *110*
| **POP server SSL port** | default *995*
| **Use spell checker server** | default *Yes* (if installed)
| **Spell server URL** | http://<example.com>:7780/aspell.php

2+|If either or both of these are changed to TRUE, the proxy setting on the
mailbox store are enabled in preparation for setting up zimbra proxy.

| *Configure for use with mail proxy. | default *FALSE*
| *Configure for use with web proxy. | default *FALSE*

| *Enable version update checks.* | {product-name} automatically
checks to see if a new {product-name} update is available. The
default is TRUE.

| *Enable version update notifications.*
a| This enables automatic notification when updates are available
when this is set to TRUE. + 
*Note:* The software update information can be viewed from the
Administration Console Tools Overview pane.

| *Version update notification email.*
| This is the email address of the account to be notified
when updates are available. The default is to send the notification
to the admin’s account.

| *Version update source email.*
| This is the email address of the account that sends the email
notification. The default is the admin’s account.

| *zimbra-spell*
|(optional) When installed, it is automatically enabled.

| *Default Class of Service Configuration*
a|This menu section lists major new features for the {product-name}
release and whether the feature is enabled or not. When you change the
feature setting during {product-name} installation, you change the
default COS settings Having this control, lets you decide when to
introduce new features to your users.

| c) Collapse menu
| Allows you to expand or collapse the menu.

| r) Start servers after configuration
| When the installation and configuration is complete, if this is set to
**Yes**, the Zimbra server is automatically started.

| s) Save config to file
| At any time during the installation, you can save the configuration to file.

| x) Expand menu
| Expand menus to see the underlying options

| q) Quit
| Quit can be used at any time to quit the installation.
|========================
