[[Configuring_High-Fidelity_Document_Preview]]
== Configuring High-Fidelity Document Preview ({product-edition-commercial} Only)
:toc:

The high-fidelity document preview feature requires the installation of
LibreOffice or the LibreOffice-headless package, depending on the
operating system you are running.

If LibreOffice is installed, the system is automatically configured
to use high-fidelity document preview. If LibreOffice is not
installed, the preview engine from prior {product-name} releases
is used.

This can be accomplished with the appropriate Linux distribution's
package management systems:

* For RHEL, install the libreoffice-headless package:

----
yum install libreoffice
yum install libreoffice-headless
----

* For SLES, install libreoffice:

----
yast2 -i libreoffice
----

* For Ubuntu, install libreoffice:

----
apt-get install libreoffice
----

[[Install_Language_and_Font_Packages]]
=== Install Language and Font Packages

Confirm you have the appropriate language packs or fonts installed for
LibreOffice to properly view documents and attachments. For example:

* If using Ubuntu 12.04 and viewing East Asian languages, be sure to install:

----
apt-get install libreoffice-l10n-*
apt-get install ttf-vlgothic
----

* If using Ubuntu 14.04 and viewing East Asian languages, be sure to install:

----
apt-get install libreoffice-l10n-*
apt-get install fonts-vlgothic
----

* If using RHEL, be sure to install:

----
yum install libreoffice-langpack-xx
----
