[[Installing_Zimbra_Collaboration_Software]]
= Installing {product-name} Software
:toc:

*Important:* Before you begin, make sure to:

* ({product-edition-commercial} Only) Store your license in a directory folder on
your server as it is needed to complete your installation of {product-name}
* Confirm you have the latest system requirements and prerequisites for
installing {product-name}.

Open an SSH session to the {product-short} server and follow the steps below:

1. Log in as root to the {product-short} server and cd to the directory where
   the {product-name} archive tar file is saved (cd /var/<tmp>). Type
   the following commands:
   * Unpack the file: `tar xvzf [zcsfullfilename.tgz]`
   * Change to the correct directory: `cd [zcsfullfilename]`
   * Begin the installation: `./install.sh`
+
--
[source%nowrap,bash]
....
root@mailhost:/tmp# tar xzvf zcs*.tgz
zcs-NETWORK-8.8.3_GA_1872.UBUNTU16_64.20170905143325/
zcs-NETWORK-8.8.3_GA_1872.UBUNTU16_64.20170905143325/packages/
.
.
.
zcs-NETWORK-8.8.3_GA_1872.UBUNTU16_64.20170905143325/install.sh
zcs-NETWORK-8.8.3_GA_1872.UBUNTU16_64.20170905143325/README.txt
....
--

2. The *install.sh* script reviews the installation software to verify that the
{product-short} packages are available. +
The installation process checks to see whether any of the applications
*Sendmail*, *Postfix*, *MySQL* or *MariaDB* are running.
If any of these applications are running,
you are asked to disable them. Disabling *MySQL* and *MariaDB* is *optional*
but highly recommended.
*Sendmail* and *Postfix must* be disabled for {product-name} to start correctly.
+
--
[source%nowrap,bash]
....
root@zimbraiop:/tmp/# cd zcs-NETWORK-8.8.3_GA_1872.UBUNTU16_64.20170905143325/
root@zimbraiop:/tmp/zcs-NETWORK-8.8.3_GA_1872.UBUNTU16_64.20170905143325# ./install.sh

Operations logged to /tmp/install.log.y1YeCSI5

Checking for existing installation...
    zimbra-chat...NOT FOUND
    zimbra-drive...NOT FOUND
    zimbra-imapd...NOT FOUND
    zimbra-network-modules-ng...NOT FOUND
    zimbra-ldap...NOT FOUND
    zimbra-logger...NOT FOUND
    zimbra-mta...NOT FOUND
    zimbra-dnscache...NOT FOUND
    zimbra-snmp...NOT FOUND
    zimbra-store...NOT FOUND
    zimbra-apache...NOT FOUND
    zimbra-spell...NOT FOUND
    zimbra-convertd...NOT FOUND
    zimbra-memcached...NOT FOUND
    zimbra-proxy...NOT FOUND
    zimbra-archiving...NOT FOUND
    zimbra-core...NOT FOUND
    
--

3. The {product-short} software agreement displays. Read the agreement and when +
`Do you agree with the terms of the software license agreement? [N]` +
displays, enter `Y` to continue. +
*Important:* The license agreement displays in multiple sections,
and you must accept each section of the license agreement.

4. `Use {product-short}'s package repository [Y]` +
displays, press `enter` to continue. Your system will be configured to add
the {product-short} packaging repository for *yum* or *apt-get* as appropriate
so it can install the {product-short} 3rd party packages. 
{product-short} IMAPD is meant to be installed on a multi-server environment, with
hundreds of thousands of users, and it's still a Beta Release. {product-short} recommends
to only install it for demo and evaluation purposes.*
* If installing *{product-short} Network Edition*, you will have the modules Archiving
and Convertd as an option to add to your {product-short} installation.
* It is recommended to only install {product-short}-dnscache on the MTA Servers when there are no other DNS servers (for example dnsmasq or bind) already installed and running on the same server.
+
--
[source%nowrap]
....
Checking for installable packages

Found zimbra-core (local)
Found zimbra-ldap (local)
Found zimbra-logger (local)
Found zimbra-mta (local)
Found zimbra-dnscache (local)
Found zimbra-snmp (local)
Found zimbra-store (local)
Found zimbra-apache (local)
Found zimbra-spell (local)
Found zimbra-convertd (local)
Found zimbra-memcached (repo)
Found zimbra-proxy (local)
Found zimbra-archiving (local)
Found zimbra-chat (repo)
Found zimbra-drive (repo)
Found zimbra-imapd (local)
Found zimbra-network-modules-ng (local)


Use Zimbra's package repository [Y] y

Use internal development repo [N] n
Configuring package repository

Install zimbra-ldap [Y] y

Install zimbra-logger [Y] y

Install zimbra-mta [Y] y

Install zimbra-dnscache [Y] n

Install zimbra-snmp [Y] y

Install zimbra-store [Y] y

Install zimbra-apache [Y] y

Install zimbra-spell [Y] y

Install zimbra-convertd [Y] y

Install zimbra-memcached [Y] y

Install zimbra-proxy [Y] y

Install zimbra-archiving [N] y

Install zimbra-chat [Y] y

Install zimbra-drive [Y] y

Install zimbra-imapd [Y] n            

Install zimbra-network-modules-ng [Y] y

###WARNING###

Network Modules NG needs to bind on TCP ports 8735 and 8736 in order
to operate, for inter-instance communication.
Please verify no other service listens on these ports and that 
ports 8735 and 8736 are properly filtered from public access 
by your firewall.

Please remember that the Backup NG module needs to be initialized in order
to be functional. This is a one-time operation only that can be performed
by clicking the 'Initialize' button within the Backup section of the
Network NG Modules in the Administration Console or by running
`zxsuite backup doSmartScan` as the zimbra user.

Checking required space for zimbra-core
Checking space for zimbra-store
Checking required packages for zimbra-store
     MISSING: libreoffice

###WARNING###

One or more suggested packages for zimbra-store are missing.
Some features may be disabled due to the missing package(s).


Installing:
    zimbra-core
    zimbra-ldap
    zimbra-logger
    zimbra-mta
    zimbra-snmp
    zimbra-store
    zimbra-apache
    zimbra-spell
    zimbra-convertd
    zimbra-memcached
    zimbra-proxy
    zimbra-archiving
    zimbra-chat
    zimbra-drive
    zimbra-network-modules-ng


The system will be modified.  Continue? [N] y
....
--
+
--
Also select the services to be installed on this server. To install
{product-name} on a single server, enter `Y` for the ldap, logger,
mta, snmp, store, and spell packages. If you use IMAP/POP Proxy, enter
`Y` for the Zimbra proxy package and the Zimbra Memcached package.

*Note:* Ensure that the `zimbra-memcached` package is installed on at least one of the nodes in the system
if the Proxy is installed.

*Note:* For the cross mailbox search feature, install the Zimbra Archive
package. To use the archiving and discovery feature, contact {product-provider}
sales.

The installer verifies that there is enough room to install {product-short}.
--

5. Next, type `Y` and press _Enter_ to modify the system.
+
--
* Selected packages are installed on the server.
* Checks to see if MX record is configured in DNS. The installer checks
to see if the hostname is resolvable via DNS. If there is an error, the
installer asks if you would like to change the hostname. We recommend
that the domain name have an MX record configured in DNS.
* Checks for port conflict.
--

6. At this point, the Main menu displays showing the default entries
for the {product-short} components you are installing. To expand the menu to see
the configuration values, type `X` and press _Enter_. The Main menu
expands to display configuration details for the packages being
installed. Values that require further configuration are marked with
asterisks (pass:[******]) to their left. To navigate the Main menu, select the
menu item to change. You can modify any of the defaults. For a quick
installation, accepting all the defaults, you only need to do the
following:

7. To set the appropriate time zone, enter `1` to select Common Configuration and then enter `7` for TimeZone.
Set the correct time zone.
+
--
....
Main menu

   1) Common Configuration:                                                  
   2) zimbra-ldap:                             Enabled                       
   3) zimbra-logger:                           Enabled                       
   4) zimbra-mta:                              Enabled                       
   5) zimbra-snmp:                             Enabled                       
   6) zimbra-store:                            Enabled                       
        +Create Admin User:                    yes                           
        +Admin user to create:                 admin@zimbra.io               
******* +Admin Password                        UNSET                         
        +Anti-virus quarantine user:           virus-quarantine.bcsk28oyoe@zimbra.io
        +Enable automated spam training:       yes                           
        +Spam training user:                   spam.dqxmkmf5tv@zimbra.io     
        +Non-spam(Ham) training user:          ham.pcq8excwph@zimbra.io      
        +SMTP host:                            z883.zimbra.io                
        +Web server HTTP port:                 8080                          
        +Web server HTTPS port:                8443                          
        +Web server mode:                      https                         
        +IMAP server port:                     7143                          
        +IMAP server SSL port:                 7993                          
        +POP server port:                      7110                          
        +POP server SSL port:                  7995                          
        +Use spell check server:               yes                           
        +Spell server URL:                     http://z883.zimbra.io:7780/aspell.php
        +Enable version update checks:         TRUE                          
        +Enable version update notifications:  TRUE                          
        +Version update notification email:    admin@zimbra.io               
        +Version update source email:          admin@zimbra.io               
        +Install mailstore (service webapp):   yes                           
        +Install UI (zimbra,zimbraAdmin webapps): yes                           
******* +License filename:                     UNSET                         

   7) zimbra-spell:                            Enabled                       
   8) zimbra-convertd:                         Enabled                       
   9) zimbra-proxy:                            Enabled                       
  10) Default Class of Service Configuration:                                
  11) Enable default backup schedule:          yes                           
   s) Save config to file                                                    
   x) Expand menu                                                            
   q) Quit                   

Address unconfigured (**) items  (? - help)
....
--

8. Type `r` to return to the Main menu.

9. Type `r` to return to the Main menu.

10. Enter `7` to select *zimbra-store* from the Main menu. The store
configuration menu displays.

11. Select the following from the store configuration menu:

    * Type `4` to set the Admin Password. The password must be six or more characters.
    Press _Enter_.

    * ({product-edition-commercial} only) Type `33` for *License filename* and type the
    directory and file name for the Zimbra license.
    For example, if you saved to the `/tmp` directory, you
    would type `/tmp/ZimbraLicense.xml`. If you do not have the license, you
    cannot proceed. See the section on
    <<Zimbra_License_Requirements,Zimbra License Requirements>>

    * Enable version update checks and Enable version update notifications. +
    If these are set to TRUE. {product-name} automatically checks for the
    latest {product-name} software updates and notifies the account
    that is configured in `Version update notification email`. You can modify
    this later from the administration console.

12. Type `r` to return to the Main menu.

13. If you want to change the default Class of Service settings for new
features that are listed here, type `12` for Default Class of Service
Configuration. +
Then type the appropriate number for the feature to be enabled or disabled.
Changes you make here are reflected in the default COS configuration.

14. If no other defaults need to be changed, type `a` to apply the
configuration changes. Press _Enter_
+
--
....
*** CONFIGURATION COMPLETE - press 'a' to apply
Select from menu, or press 'a' to apply config (? - help) a
....
--

16. When Save Configuration data to file appears, type "Yes" and press _Enter_.
+
--
....
Save configuration data to a file? [Yes]
....
--

17. The next request asks where to save the files. To accept the
default, press "Enter". To save the files to another directory, enter the
directory and then press Enter
+
--
....
Save config in file: [/opt/zimbra/config.16039]
Saving config in /opt/zimbra/config.16039...done.
....
--

18. When "The system will be modified - continue?" appears, type "Yes" and
press _Enter_.
+
The server is modified. Installing all the components and configuring
the server can take several minutes. Components that are installed
include spam training and documents, (wiki) accounts, time zone
preferences, backup schedules, licenses, as well as common Zimlets.
+
--
....
The system will be modified - continue? [No] y
Operations logged to /tmp/zmsetup.20160711-234517.log
Setting local config values...done.
Initializing core config...Setting up CA...done.
Deploying CA to /opt/zimbra/conf/ca ...done.
Creating SSL zimbra-store certificate...done.
Creating new zimbra-ldap SSL certificate...done.
Creating new zimbra-mta SSL certificate...done.
Creating new zimbra-proxy SSL certificate...done.
Installing mailboxd SSL certificates...done.
Installing MTA SSL certificates...done.
Installing LDAP SSL certificate...done.
Installing Proxy SSL certificate...done.
Initializing ldap...done.
.
.
Checking current setting of zimbraReverseProxyAvailableLookupTargets
Querying LDAP for other mailstores
Searching LDAP for reverseProxyLookupTargets...done.
Adding zmail.example.com to zimbraReverseProxyAvailableLookupTargets
Setting convertd URL...done.
.
.
Granting group zimbraDomainAdmins@zmail.example.com domain right +domainAdminConsoleRights on zmail.example.com...done.
Granting group zimbraDomainAdmins@zmail.example.com global right +domainAdminZimletRights...done.
Setting up global distribution list admin UI components..done.
Granting group zimbraDLAdmins@zmail.example.com global right +adminConsoleDLRights...done.
.
.
Setting default backup schedule...Done
Looking for valid license to install...license installed.
Starting servers...done.
Installing common zimlets...
        com_zimbra_attachmail...done.
        com_zimbra_phone...done.
        com_zimbra_proxy_config...done.
          .
          .
        com_zimbra_ymemoticons...done.
        com_zimbra_date...done.
Finished installing common zimlets.
Installing network zimlets...
        com_zimbra_mobilesync...done.
         .
         .
        com_zimbra_license...done.
Finished installing network zimlets.
Restarting mailboxd...done.
Creating galsync account for default domain...done.
Setting up zimbra crontab...done.


Moving /tmp/zmsetup.20160711-234517.log to /opt/zimbra/log


Configuration complete - press return to exit
....
--
