[[introduction]]
= Introduction

{product-name} includes the Zimbra MTA, the Zimbra LDAP server, and the Zimbra mailbox server.
In a single-server installation, all components are installed on one server and require no additional
manual configuration.

This installation guide is a quick start guide that describes the basic steps needed to install and configure
{product-name} in a direct network connect environment. In this environment, the Zimbra server is assigned a domain
for which it receives mail, and a direct network connection to the Internet.  When {product-name} is installed, you
will be able to log on to the Zimbra administration console to manage the domain and provision accounts.
The accounts you create are able to send and receive external email.

== Important Notice About Single Server Installations

{product-name} is designed to be the only application suite installed on the server.
As part of the installation process, {product-name} bundles and installs various other third party and open
source software, including Apache Jetty, Postfix, and OpenLDAP®.  The versions installed have been tested and
configured to work with Zimbra software. See the {product-name} Administrator Guide for a complete list of
software.

A Zimbra license is required in order to create accounts on servers running {product-name} Network Edition.
You cannot install {product-name} Network Edition without a license.

The following table shows the default port settings when {product-name} is installed.

== Zimbra Port Mapping

[cols=",",]
|========================
|Remote Queue Manager |22
|Postfix |25
|HTTP |80
|POP3 |110
|IMAP |143
|LDAP |389
|HTTPS |443
|Mailboxd IMAP SSL |993
|Mailboxd Pop SSL |995
|Mailboxd LMTP |7025
|========================

**Important:** You cannot have any other web server, database, LDAP, or MTA server running, when you install
{product-name}. If you have installed any of those applications before you install Zimbra software, disable them.
During {product-name} installation, Zimbra makes global system changes that may break applications that are on
your server.
