[[Zimbra_Licenses]]
= {product-short} Licensing ({product-edition-commercial} Only)
:toc:

{product-name} licensing gives administrators better visibility and
control into the licensed features they plan to deploy. The following
is a summary of the feature attributes of a {product-name}
{product-edition-commercial} license.

* *Accounts limit.* The maximum number of accounts you can create and
the number of accounts created are shown.
* *Mobile accounts limit.* The maximum number of accounts that can have
the native mail mobile feature enabled.
* **Touch Client accounts limit**. The maximum number of accounts that
can have the touch client mobile feature enabled.
* **MAPI accounts limit**. The maximum number of accounts that can use
{product-short} Connector for Microsoft Outlook (ZCO).
* *Exchange Web Services (EWS) accounts limit.* The maximum number of
accounts that can use EWS for connecting to an Exchange server.
* *High-Fidelity Document Preview:* The maximum number of accounts that
can use the High-Fidelity document preview facility. LibreOffice must be
installed.
* *Archiving Accounts limit.* The maximum number of archive accounts
that can be created. The archive feature must be installed.

[[Zimbra_License_Requirements]]
== {product-short} License Requirements

A {product-short} license is required in order to create accounts in
the {product-edition-commercial} of {product-name}.

Several types of licenses are available:

* **Trial**.  You can obtain a free Trial license from the {product-provider} website,
at https://www.zimbra.com. The trial license allows you to create up to
50 users. It expires in 60 days.
* *Trial Extended.*  You can obtain a Trial Extended license from {product-provider}
Sales by contacting sales@zimbra.com or calling 1-972-407-0688. This
license allows you to create up to 50 users and is valid for an extended
period of time.
* *Subscription.*  You must purchase the {product-short} Subscription license. This
license is valid for a specific {product-name} system and is
encrypted with the number of {product-short} accounts (seats) you have purchased,
the effective date, and expiration date of the subscription license.
* *Perpetual.*  You must purchase the {product-short} Perpetual license. This
license is similar to a subscription license and is valid for a specific
{product-name} system, is encrypted with the number of {product-short}
accounts (seats) you have purchased, the effective date, and an
expiration date of 2099-12-31. When you renew your support agreement, no
new perpetual license is sent to you, but your Account records in the
systems is updated with your new support end date.

[[License_Usage_by_Zimbra_Collaboration_Account_Type]]
== License Usage by {product-name} Account Type

A mailbox license is required for an account assigned to a person,
including accounts created for archiving. Distribution lists, aliases,
locations and resources do not count against the license.

Below is a description of types of {product-name} accounts and if they
impact your license limit.

* *System accounts.* System accounts are specific accounts used by
{product-name}. They include the spam filter accounts for junk mail
(spam and ham), virus quarantine account for email messages with
viruses, and GALsync account if you configure GAL for your domain. *Do
not delete these accounts!* These accounts do not count against your
license.
* *Administrator account.*  Administrator accounts count against your license.
* *User accounts.*  User accounts count against your license account limit.

When you delete an account, the license account limit reflects the change.

* *Alias account.*  Aliases do not count against your license.
* *Distribution list.*  Distribution lists do not count against your license.
* *Resource account.*  Resource accounts (location and resources) do not
count against your {product-name} license.

[[License_Activation]]
== License Activation

All {product-edition-commercial} installations require license activation. New
installations have a 10 day grace period from the license issue date
before requiring activation. Your license can be activated from the
administration console by selecting *Configure>Global Settings>License*,
then clicking *Activate License* in the toolbar. You can also
activate your license from the command line interface.

Upgraded {product-name} versions require an immediate activation
to maintain network feature functionality.

[[Automatic_License_Activation]]
== Automatic License Activation

Licenses are automatically activated if the {product-name} server
has a connection to the Internet and can communicate with the {product-short}
License server. If you are unable to automatically activate your
license, see the next section on
<<Manual_License_Activation,Manual License Activation>>

[[Manual_License_Activation]]
== Manual License Activation

For systems that do not have external access to the {product-short} License
server, you can use the {product-short} Support Portal to manually activate your
license. Go to the {product-provider} website at https://www.zimbra.com and click on the
Support page to display the {product-short} Technical Support page. Click on the
Support Portal Login button to display the {product-short} Support Portal page.
Enter your email and password to log in.

[[License_Not_Installed_or_Activated]]
== License Not Installed or Activated

If you fail to install or activate your {product-name} server
license, the following scenarios describe how your {product-name}
server will be impacted.

* *License is not installed.*  If a license is not installed, the
{product-name} server defaults to single user mode where all features
limited by license are limited to one user.
* *License is not valid.*  If the license file is forged or could not be
validated for other reasons, the {product-name} server defaults to
single user mode.
* *License is not activated.*  A license activation grace period is 10
days. If for some reason the license is never activated, the
{product-name} server defaults to single user mode.
* *License is in future.*  If the license starting date is still in the
future, the {product-name} server defaults to single user mode.
* *License is in grace period.*  If the license ending date has passed and
is within the 30 day grace period, all features limited by license are
still enabled, but administrators may see license renewal prompts.
* *License expired.*  If the license ending date has passed and the 30 day
grace period expired, the {product-name} server defaults to the
feature set of the Open Source Edition.

[[Obtaining_a_License]]
== Obtaining a License

Go to {product-provider}’s Website https://www.zimbra.com to obtain a trial license
from the Network Downloads area.  Contact {product-provider} sales regarding a trial
extended license, or to purchase a subscription license or perpetual
license, by emailing sales@zimbra.com or calling 1-972-407-0688.

The subscription and perpetual license can only be installed on the
{product-name} system for which it is purchased. Only one {product-short}
license is required for your {product-name} environment. This
license sets the number of accounts that can be created.

Current license information, including the number of accounts purchased,
the number of accounts used, and the expiration date, can be viewed from
the administration console's *Configure>Global Settings>License* page.
