[[multiple_server_install]]
= Multiple-Server Installation

The multiple-server installation is straight-forward and easy to run.
You run the same installation script on each server, select the
component(s) to install, and use the menu to configure the system.

When the server installation is complete after final set-up and server
nnconfiguration steps are run, the servers are started and the status is
displayed.

*Order of Installation*

1. {product-abbrev} LDAP server(s)
2. {product-abbrev} MTA server(s)
3. {product-abbrev} Proxy server(s)
4. {product-abbrev} Mailbox server(s) options:
    ** Zimbra Mailbox Server, which includes the mailstore services and
       webapp services (mailstore server + UI server)
    ** Zimbra Web Application Server Split mode, which includes:
        *** a Zimbra mailstore server (mailstore server)
        *** a Zimbra webapp server (UI server)

[NOTE]
Zimbra-proxy is normally installed on the MTA server or you can install it on its own server.

[IMPORTANT]
Do not manually create the user ‘zimbra’ before running the {product-abbrev}
installation. The installation automatically creates this user and sets up
its environment.

[IMPORTANT]
Before you start, verify that the system clocks are synced on all servers.

[[starting_multiple_server_install]]
== Starting the Installation Process

[IMPORTANT]
====
_Before you begin, make sure to:_

ifdef::networkeditiondoc[]
* Store your license in a directory folder on your server as it is needed to
  complete your installation of {product-name}. For more information about
  licenses, see <<Intro_license, {product-name} License>> and
  <<Zimbra_License_Requirements,Zimbra License Requirements>>
  ({product-edition-commercial} only)
endif::networkeditiondoc[]
* Confirm you have the latest system requirements and prerequisites for
  installing {product-name}, as described in
  <<System_Requirements, System Requirements for {product-name}>>
====

For the latest {product-name} software downloads, go to
https://www.zimbra.com. +
Save the {product-name} *tar* file to the computer from which you are
installing the software.

[NOTE]
_The screen shots are examples of the {product-name} installation
script. The actual script may be different._

Step 1 through step 4 are performed for each server to be installed.

Open an SSH session to the {product-short} server and follow the steps below:

1.  Log in as *root* to the {product-name} server and *cd* to the
    directory where the {product-name} archive file is saved
    (cd /var/<tmp>). Type the following commands.
+
--
    ** `tar xzvf [zcs.tgz]` to unpack the file
    ** `cd [zcs filename]` to change to the correct directory. The file
       name includes the release and build date.
    ** `./install.sh` to begin the installation.
--
+
--
[NOTE]
_As the installation proceeds, press_ *Enter* _to accept the
defaults that are shown in brackets_ [ ] _or enter the appropriate
answer for your configuration._

[source%nowrap,bash]
....
root@mailhost:/tmp# tar xzvf zcs.tgz
zcs-NETWORK-8.7.6_GA_1776.UBUNTU16_64.20170326144124/
zcs-NETWORK-8.7.6_GA_1776.UBUNTU16_64.20170326144124/packages/
.
.
.
zcs-NETWORK-8.7.6_GA_1776.UBUNTU16_64.20170326144124/install.sh
zcs-NETWORK-8.7.6_GA_1776.UBUNTU16_64.20170326144124/README.txt

root@zimbraiop:/tmp/# cd zcs-NETWORK-8.7.6_GA_1776.UBUNTU16_64.20170326144124/
root@zimbraiop:/tmp/zcs-NETWORK-8.7.6_GA_1776.UBUNTU16_64.20170326144124# ./install.sh

Operations logged to /tmp/install.log.y1YeCSI5
.
.
.
....
--

2. The *install.sh* script reviews the installation software to verify that the
   {product-short} packages are available. +
   The installation process checks to see whether any of the applications
   *Sendmail*, *Postfix*, *MySQL* or *MariaDB* are running. +
   If any of these applications are running, you are asked to disable them. +
   Disabling *MySQL* and *MariaDB* is *optional* but highly recommended. +
   *Sendmail* and *Postfix* *MUST* be disabled for {product-name} to start correctly.
+
--
[source%nowrap,bash]
....
root@zimbraiop:/tmp/zcs-NETWORK-8.7.6_GA_1776.UBUNTU16_64.20170326144124# ./install.sh


Operations logged to /tmp/install.log.y1YeCSI5
Checking for existing installation...
    zimbra-chat...NOT FOUND
    zimbra-drive...NOT FOUND
    zimbra-ldap...NOT FOUND
    zimbra-logger...NOT FOUND
    zimbra-mta...NOT FOUND
    zimbra-dnscache...NOT FOUND
    zimbra-snmp...NOT FOUND
    zimbra-store...NOT FOUND
    zimbra-apache...NOT FOUND
    zimbra-spell...NOT FOUND
    zimbra-convertd...NOT FOUND
    zimbra-memcached...NOT FOUND
    zimbra-proxy...NOT FOUND
    zimbra-archiving...NOT FOUND
    zimbra-core...NOT FOUND
.
.
.
....
--

3. The {product-short} software agreement displays. Read the agreement and when + 
`Do you agree with the terms of the software license agreement? [N]` + 
displays, enter `Y` to continue.
+
--
[IMPORTANT]
The license agreement displays in multiple sections,
and you must accept each section of the license agreement.
--


4. `Use {product-short}'s package repository [Y]` + 
displays, press `enter` to continue. Your system will be configured to add
the {product-short} packaging repository for *yum* or *apt-get* as appropriate
so it can install the {product-short} 3rd party packages.
+
--
[source%nowrap]
....
Checking for installable packages

Found zimbra-core (local)
Found zimbra-ldap (local)
Found zimbra-logger (local)
Found zimbra-mta (local)
Found zimbra-dnscache (local)
Found zimbra-snmp (local)
Found zimbra-store (local)
Found zimbra-apache (local)
Found zimbra-spell (local)
Found zimbra-convertd (local)
Found zimbra-memcached (repo)
Found zimbra-proxy (local)
Found zimbra-archiving (local)
Found zimbra-chat (repo)
Found zimbra-drive (repo)



Use Zimbra's package repository [Y] y
Configuring package repository
....
--

5. Next, select the packages to be installed on this server.
+
--
[NOTE]
For the cross mailbox search feature, install the {product-short} Archive
package. To use the archiving and discovery feature, contact {product-provider}
sales.
--
+
The installer verifies that there is enough room to install {product-short}.

6. Next, the installer checks to see that the prerequisite packages are
   installed as listed in the Other Dependencies section of the
   <<System_Requirements, System Requirements for {product-name}>>
+
--
[NOTE]
_Before the Main menu is displayed, the installer checks to see if the
hostname is resolvable via DNS and if there is an error asks
you if would like to change the hostname. The domain name should have an
MX record configured in DNS._
--

[[install_ldap_master]]
== Installing {product-short} LDAP Master Server

You must configure the {product-abbrev} LDAP Master server before you can install
other {product-abbrev} servers. You can set up LDAP replication, configuring a
master LDAP server and replica LDAP servers, either configuring all LDAP
servers now or after you set up the initial {product-name} servers. See the
section on <<ldap-replication,Configuring LDAP Replication>>

1. Follow steps 1 through 4 in
   <<starting_multiple_server_install,Starting the Installation Process>>
   to open an SSH session to the LDAP server, log on to the server as *root*,
   and unpack the {product-abbrev} software.
2. Type `y` and press _Enter_ to install the `zimbra-ldap` package. +
   The `zimbra-mta`, `zimbra-store` and `zimbra-logger` packages should be
   marked `n`.
+
--
[source%nowrap]
....
Install zimbra-ldap [Y] Y

Install zimbra-logger [Y] N

Install zimbra-mta [Y] N

Install zimbra-dnscache [Y] N

Install zimbra-snmp [Y] N

Install zimbra-store [Y] N

Install zimbra-apache [Y] N

Install zimbra-spell [Y] N

Install zimbra-convertd [Y] N

Install zimbra-memcached [Y] N

Install zimbra-proxy [Y] N

Install zimbra-archiving [N] N

Install zimbra-chat [Y] N

Install zimbra-drive [Y] N

Checking required space for zimbra-core

Installing:
    zimbra-core
    zimbra-ldap

The system will be modified.  Continue? [N]
....
--

3. Type `Y`, and press _Enter_ to modify the system. The selected
   packages are installed on the server.
+
The Main menu displays the default entries for the Zimbra component you
are installing. +
To expand the menu to see the configuration values, type `x` and press _Enter_. +
The main menu expands to display configuration details for the package
being installed.
+
--
[NOTE]
Values that require further configuration are marked with asterisks (`*`).
--
+
To navigate the Main menu, select the menu item to change. You can
modify any of the values. See the section
<<main_menu_options,Main Menu options>>
for a description of the Main menu.
+
--
[source%nowrap]
....
Main menu

   1) Common Configuration:
   2) zimbra-ldap:                             Enabled
   3) Enable default backup schedule:          yes
   s) Save config to file
   x) Expand menu
   q) Quit

*** CONFIGURATION COMPLETE - press 'a' to apply
Select from menu, or press 'a' to apply config (? - help)
....
--

4.  Type `1` to display the *Common Configuration* submenu.
+
--
[source%nowrap]
....
Common configuration

   1) Hostname:                                ldap1.example.com
   2) Ldap master host:                        ldap1.example.com
   3) Ldap port:                               389
   4) Ldap Admin password:                     set
   5) Store ephemeral attributes outside Ldap: no
   6) Secure interprocess communications:      yes
   7) TimeZone:                                America/Mexico_City
   8) IP Mode:                                 ipv4
   9) Default SSL digest:                      sha256

Select, or 'r' for previous menu [r]
....
--

5.  Type `4` to display the automatically generated LDAP admin password.
+
--
[source%nowrap]
....
Select, or 'r' for previous menu [r] 4

Password for ldap admin user (min 6 characters): [bEyMZxNxq]
....
--
+
--
You can change this password. +
Write down the LDAP password, the LDAP host name and the LDAP port.

[source%nowrap]
....
LDAP Admin Password _______________________
LDAP Host name      _______________________
LDAP Port           _______________________
....
--
[NOTE]
You must configure this information when you install the mailbox servers
and the MTA servers.

6. Type `7` to set the correct time zone.
+
--
[source%nowrap]
....
1 Africa/Algiers
.
.
.
94 Europe/London
.
.
.
109 Pacific/Tongatapu
110 UTC
Enter the number for the local timezone: [110] 94
....
--

7. Type `r` to return to the Main menu.

8.  From the Main menu, type `2` for *zimbra-ldap* to view the
    *Ldap configuration* settings.
+
--
[source%nowrap]
....
Ldap configuration

   1) Status:                                  Enabled
   2) Create Domain:                           yes
   3) Domain to create:                        ldap-1.example.com
   4) Ldap root password:                      set
   5) Ldap replication password:               set
   6) Ldap postfix password:                   set
   7) Ldap amavis password:                    set
   8) Ldap nginx password:                     set
   9) Ldap Bes Searcher password:              set

Select, or 'r' for previous menu [r]
....
--

9. Type `3` for *Domain to create* to change the default domain name to
   the main domain name you want to use for your network, (e.g. *example.com*).

10. The passwords listed in the *LDAP configuration* menu are automatically
    generated.
+
--
If you want to change the passwords for LDAP root, LDAP replication,
LDAP Postfix, LDAP Amavis, and LDAP Nginx, enter the
corresponding number `4` through `8` and change the passwords.

[source%nowrap]
....
Ldap replication password _____________________
Ldap postfix password     _____________________
Ldap amavis password      _____________________
Ldap nginx password       _____________________
....

[NOTE]
You need these passwords when configuring the MTA and the LDAP
replica servers. Write them down.
--

11. When changes to the LDAP configuration menu are complete:
+
--
[source%nowrap]
....
*** CONFIGURATION COMPLETE - press 'a' to apply
Select from menu, or press 'a' to apply config (? - help) a
Save configuration data to a file? [Yes]
Save config in file: [/opt/zimbra/config.8381]
Saving config in /opt/zimbra/config.8381...done
....
--

    ** enter `r` to return to the main menu.
    ** Type `a` to apply the configuration changes.
    ** When `Save configuration data to file` appears, +
       type `Yes` and press _Enter_.
    ** The next request asks where to save the files. +
       To accept the default, press _Enter_. +
       To save the files to another directory, enter the directory
       and press _Enter_.

12. When `The system will be modified - continue? [No]` appears, +
    type `y` and press _Enter_.
+
--
The server is modified. Installing all the components and configuring
the server can take a few minutes. This includes but is not limited to
setting local config values, creating and installing SSL certificates,
setting passwords, timezone preferences, and starting the servers, among
other processes.
--

13. When `Configuration complete - press return to exit` displays,
    press _Enter_.
+
--
[source%nowrap]
....
*** CONFIGURATION COMPLETE - press 'a' to apply
Select from menu, or press 'a' to apply config (? - help) a
Save configuration data to a file? [Yes]
Save config in file: [/opt/zimbra/config.8381]
Saving config in /opt/zimbra/config.8381...done.
The system will be modified - continue? [No] y
Operations logged to /tmp/zmsetup.20170302-133132.log
Setting local config values...done.
.
.
.
Starting servers...done.
Skipping creation of default domain GAL sync account - not a service node.
Setting up zimbra crontab...done.


Moving /tmp/zmsetup.20170302-133132.log to /opt/zimbra/log


Configuration complete - press return to exit
....

The installation of the LDAP server is complete.
--

[[install_mailbox]]
== Installing the {product-short} Mailbox Server

The *zimbra-store* package can be installed with the LDAP server, the MTA
server, or as a separate mailbox server.

You can have the following configuration options:

* The *{product-short} Mailbox Server* containing mailstore services and webapp
services (mailstore server + UI server)

or

* The *Zimbra Web Application Server Split*, which includes:

** Mailstore server providing the backend SOAP/REST functionality
** UI server providing the web UI functionality (static html/js/css content)

You can have more than one of the above configurations.
In a web application server split environment, you must have at least
one mailstore server and one UI server in your configuration.

[IMPORTANT]
A web application server split environment must have proxy and
memcached installed.

The Zimbra license file can be installed on one of the mailbox
servers during the installation.
If you do not have a license file, you can install it from the
administration console when the {product-name} install is complete.
See <<Zimbra_License_Requirements,Zimbra License Requirements>>

=== Install Zimbra Mailbox Services

1. Follow steps 1 through 4 in
   <<starting_multiple_server_install,Starting the Installation Process>>
   to open an SSH session to the Mailbox server, log on to the server as
   *root*, and unpack the {product-abbrev} software.

2. Type `y` and press _Enter_ to install the *zimbra-logger* package
   (optional and only on one mail server) and *zimbra-store*.
   In the following screen shot example, the packages to be installed are emphasized.
+
--
[NOTE]
_If SNMP is being used, the SNMP package is installed on every
{product-short} server. Mark_ `y`

[source%nowrap]
....
Install zimbra-ldap [Y] N

Install zimbra-logger [Y] Y

Install zimbra-mta [Y] N

Install zimbra-dnscache [Y] N

Install zimbra-snmp [Y] Y

Install zimbra-store [Y] Y

Install zimbra-apache [Y] Y

Install zimbra-spell [Y] Y

Install zimbra-convertd [Y] Y

Install zimbra-memcached [Y] N

Install zimbra-proxy [Y] N

Install zimbra-archiving [N] Y

Install zimbra-chat [Y] Y

Install zimbra-drive [Y] Y

Checking required space for zimbra-core
Checking space for zimbra-store
Checking required packages for zimbra-store
     FOUND: libreoffice-1:4.2.8-0ubuntu4
zimbra-store package check complete.

Installing:
    zimbra-core
    zimbra-logger
    zimbra-snmp
    zimbra-store
    zimbra-apache
    zimbra-spell
    zimbra-convertd
    zimbra-archiving
    zimbra-chat
    zimbra-drive

The system will be modified.  Continue? [N]
....
--

3. Type `Y`, and press _Enter_ to modify the system. The selected
   packages are installed on the server.
+
The Main menu displays the default entries for the Zimbra component you
are installing. +
To expand the menu to see the configuration values, type `x` and press _Enter_. +
The main menu expands to display configuration details for the package
being installed.
+
--
[NOTE]
Values that require further configuration are marked with asterisks (`*`).
--
+
To navigate the Main menu, select the menu item to change. You can
modify any of the values. See the section
<<main_menu_options,Main Menu options>>
for a description of the Main menu.
+
--
[source%nowrap]
....
Main menu

   1) Common Configuration:
        +Hostname:                             mailstore-1.example.com
******* +Ldap master host:                     UNSET
        +Ldap port:                            389
******* +Ldap Admin password:                  UNSET
        +Store ephemeral attributes outside Ldap: no
        +Secure interprocess communications:   yes
        +TimeZone:                             UTC
        +IP Mode:                              ipv4
        +Default SSL digest:                   sha256

   2) zimbra-logger:                           Enabled
   3) zimbra-snmp:                             Enabled
   4) zimbra-store:                            Enabled
        +Create Admin User:                    yes
        +Admin user to create:                 admin@mailstore-1.example.com
******* +Admin Password                        UNSET
        +Anti-virus quarantine user:           virus-quarantine.mgpgruxx@mailstore-1.example.com
        +Enable automated spam training:       yes
        +Spam training user:                   spam.qgku2xsq@mailstore-1.example.com
        +Non-spam(Ham) training user:          ham.y49bbzuis@mailstore-1.example.com
******* +SMTP host:                            UNSET
        +Web server HTTP port:                 8080
        +Web server HTTPS port:                8443
        +Web server mode:                      https
        +IMAP server port:                     7143
        +IMAP server SSL port:                 7993
        +POP server port:                      7110
        +POP server SSL port:                  7995
        +Use spell check server:               yes
        +Spell server URL:                     http://mailstore-1.example.com:7780/aspell.php
        +Enable version update checks:         TRUE
        +Enable version update notifications:  TRUE
        +Version update notification email:    admin@mailstore-1.example.com
        +Version update source email:          admin@mailstore-1.example.com
        +Install mailstore (service webapp):   yes
        +Install UI (zimbra,zimbraAdmin webapps): yes
******* +License filename:                     UNSET

   5) zimbra-spell:                            Enabled
   6) zimbra-convertd:                         Enabled
   7) Default Class of Service Configuration:
   8) Enable default backup schedule:          yes
   s) Save config to file
   x) Expand menu
   q) Quit
  
Address unconfigured (**) items  (? - help)
....
--

4.  Type `1` to display the *Common Configuration* submenu.
+
--
[source%nowrap]
....
Common configuration

   1) Hostname:                                mailstore-1.example.com
** 2) Ldap master host:                        UNSET
   3) Ldap port:                               389
** 4) Ldap Admin password:                     UNSET
   5) Store ephemeral attributes outside Ldap: no
   6) Secure interprocess communications:      yes
   7) TimeZone:                                UTC
   8) IP Mode:                                 ipv4
   9) Default SSL digest:                      sha256
....

The mailbox server hostname is displayed.

[IMPORTANT]
You must change the LDAP master host name and password to be the
values configured on the LDAP server.

** Type `2`, press _Enter_, and type the LDAP host name.
   (*ldap-1.example.com* in this example.)
** Type `4`, press _Enter_, and type the LDAP password. +
   To obtain the LDAP password, you will need to log on to the
   LDAP server as the `zimbra` user, and run the following command:

[source%nowrap,bash]
....
zmlocalconfig -s zimbra_ldap_password
....

After you set these values, the server immediately contacts the LDAP
server. If it cannot contact the server, you cannot proceed.
--

5. Type `7` to set the correct time zone.
+
--
[source%nowrap]
....
1 Africa/Algiers
.
.
.
94 Europe/London
.
.
.
109 Pacific/Tongatapu
110 UTC
Enter the number for the local timezone: [110] 94
....
--

6. Type `r` to return to the Main menu.

7.  From the Main menu, type `4` for *zimbra-store* to view the
    *Store configuration* settings.
+
--
[source%nowrap]
....
Store configuration

   1) Status:                                  Enabled
   2) Create Admin User:                       yes
   3) Admin user to create:                    admin@mailstore-1.example.com
** 4) Admin Password                           UNSET
   5) Anti-virus quarantine user:              virus-quarantine.orulkdewtz@mailstore-1.example.com
   6) Enable automated spam training:          yes
   7) Spam training user:                      spam.udbnonsavi@mailstore-1.example.com
   8) Non-spam(Ham) training user:             ham.3ptgqja0f@mailstore-1.example.com
** 9) SMTP host:                               UNSET
  10) Web server HTTP port:                    8080
  11) Web server HTTPS port:                   8443
  12) HTTP proxy port:                         80
  13) HTTPS proxy port:                        443
  14) Web server mode:                         https
  15) IMAP server port:                        7143
  16) IMAP server SSL port:                    7993
  17) IMAP proxy port:                         143
  18) IMAP SSL proxy port:                     993
  19) POP server port:                         7110
  20) POP server SSL port:                     7995
  21) POP proxy port:                          110
  22) POP SSL proxy port:                      995
  23) Use spell check server:                  yes
  24) Spell server URL:                        http://mailstore-1.example.com:7780/aspell.php
  25) Configure for use with mail proxy:       TRUE
  26) Configure for use with web proxy:        TRUE
  27) Enable version update checks:            TRUE
  28) Enable version update notifications:     TRUE
  29) Version update notification email:       admin@mailstore-1.example.com
  30) Version update source email:             admin@mailstore-1.example.com
  31) Install mailstore (service webapp):      yes
  32) Install UI (zimbra,zimbraAdmin webapps): yes
**33) License filename:                        UNSET

Select, or 'r' for previous menu [r]
....
--

8. Type `4` and set the password for the administrator account.
   The password is case sensitive and must be a minimum of six
   characters.  During the install process, the admin account is
   provisioned on the mailbox store server. You log on to the
   administration console with this password.
+
--
[NOTE]
_By default, the domain name portions of the email addresses for the
Admin user, Anti-virus quarantine user, Spam training user and Non-spam(Ham)
training user, are set to be the zimbra mailstore server address.
You may want to change these to be the {product-name} primary domain address
instead.  (*example.com* in this example)_
--

9. Type the corresponding number to set the `SMTP host`.  This is the
   mta-server host name.

10. Type the corresponding number if you want to change the default
    `Web server mode`. The communication protocol options are
    HTTP, HTTPS, mixed, both or redirect.
+
--
** *Mixed* mode uses HTTPS for logging in and HTTP for normal session
   traffic
** *Both* mode means that an HTTP session stays HTTP, including during
   the login phase, and an HTTPS session remains HTTPS throughout,
   including the login phase.
** *Redirect* mode redirects any users connecting via HTTP to an HTTPS
   connection.

All modes use SSL encryption for back-end administrative traffic.
--

11. If you are configuring proxy servers, type the corresponding number
    to enable the servers. When you enable these, the mail server port
    and proxy port numbers are automatically changed.
	See <<_configuration_during_installation>>.

12. If you install the *{product-short}-spell* package, it should be installed
    on every mailstore. +
    The hostname portion of the http address for each should be the hostname
    of the mailstore server it is installed on.

13. `Enable version update checks` and `Enable version update notifications`
    are set to TRUE. {product-name} automatically checks for the latest
    {product-name} software updates and notifies the account that is
    configured in Version update notification email.
    You can modify this later from the administration console.

14. If the *{product-short}-proxy* package is not installed on the mailbox
    server, two menu options are displayed so you can preconfigure the
    mailbox server for use with the zimbra proxy server:
+
--
** Configure for use with mail proxy
** Configure for use with web proxy

Set either or both of these to TRUE if you are going to set up
{product-short}-proxy. +
The {product-short}-proxy ports display in the menu when these are set
to TRUE.
--

15. *({product-edition-commercial} only)*.  Type the corresponding menu
    number to install the Zimbra license file. +
    Enter the location of the Zimbra license file. For example, if you
    saved the license file to the tmp directory,
    you would type `/tmp/ZCSLicense.xml`. +
    You cannot proceed without a license.

16. Configure the mailstore and webapp services either on a single
    server or in a split server configuration.
+
--
** To install mailstore server only, set
  `Install UI (zimbra,zimbraAdmin webapps)` value to `no`,
   which will exclude the web services.
** To install UI server only, set the
   `Install mailstore (service webapp)` value to `no`,
   which will exclude mailstore services.
** To install both the mailstore and UI services on the same server,
   confirm the values for +
   `Install mailstore (service webapp)` and +
   `Install UI (zimbra,zimbraAdmin webapps)` +
   are both set to `yes`.  The default is `yes`.

[NOTE]
See the release notes for additional configuration information
for installing a split node environment.
--

17. Type `r` to return to the Main menu.

18. Review the Default Class of Service Configuration settings.
    If you want to change the COS default configuration of
    these features, type the number for the
    `Default Class of Service Configuration` Then type the
    corresponding number for the feature to be enabled or disabled. +
    The default COS settings are adjusted to match.

19.  When the mailbox server is configured, return to the Main menu
     and type `a` to apply the configuration changes. +
     Press _Enter_ to save the configuration data.

20. When Save Configuration data to file appears, type `Yes` and press _Enter_.
+
--
....
Save configuration data to a file? [Yes]
....
--

21. The next request asks where to save the files. To accept the
default, press _Enter_. To save the files to another directory, enter the
directory and then press Enter
+
--
....
Save config in file: [/opt/zimbra/config.16039]
Saving config in /opt/zimbra/config.16039...done.
....
--

22. When `The system will be modified - continue?` appears, type `Yes` and
press _Enter_.
+
The server is modified. Installing all the components and configuring
the server can take several minutes. This includes installing SSL
certificates, setting passwords, setting ports, installing skins
and common zimlets, setting time zone preferences, backup schedules
and starting the servers, among other processes.
+
--
....
The system will be modified - continue? [No] y
Operations logged to /tmp/zmsetup.20160711-234517.log
Setting local config values...done.
.
.
.
Configuration complete - press return to exit
....
--

23. When `Configuration complete - press return to exit` displays,
    press _Enter_

The installation of the mailbox server is complete.

== Installing {product-short} MTA on a Server


When {product-short}-mta is installed, the LDAP host name and the
{product-short} LDAP password must be known to the MTA server.
If not, the MTA cannot contact the LDAP server and is not able to
complete the installation.

1. Follow steps 1 through 4 in
   <<starting_multiple_server_install,Starting the Installation Process>>
   to open an SSH session to the MTA server, log on to the server as
   *root*, and unpack the {product-abbrev} software.

2. Type `y` and press _Enter_ to install the *zimbra-mta* and 
   *zimbra-dnscache* packages.  The other packages should be marked `n`.
   In the following screen shot example, the packages to be installed are emphasized.
+
--
[NOTE]
_If SNMP is being used, the SNMP package is installed on every
{product-short} server. Mark_ `y`

[source%nowrap]
....
Select the packages to install

Install zimbra-ldap [Y] n

Install zimbra-logger [Y] n

Install zimbra-mta [Y] y

Install zimbra-dnscache [Y] y

Install zimbra-snmp [Y] n

Install zimbra-store [Y] n

Install zimbra-apache [Y] n

Install zimbra-spell [Y] n

Install zimbra-memcached [Y] n

Install zimbra-proxy [Y] n
Checking required space for zimbra-core

Installing:
    zimbra-core
    zimbra-mta
    zimbra-dnscache

The system will be modified.  Continue? [N] y
Installing packages
....
--

3. Type `Y`, and press _Enter_ to modify the system. The selected
   packages are installed on the server.
+
The Main menu displays the default entries for the Zimbra component you
are installing. +
To expand the menu to see the configuration values, type `x` and press _Enter_. +
The main menu expands to display configuration details for the package
being installed.
+
--
[NOTE]
Values that require further configuration are marked with asterisks (`*`).
--
+
To navigate the Main menu, select the menu item to change. You can
modify any of the values. See the section
<<main_menu_options,Main Menu options>>
for a description of the Main menu.
+
--
[source%nowrap]
....
Main menu

   1) Common Configuration:
        +Hostname:                             mta-1.example.com
******* +Ldap master host:                     UNSET
        +Ldap port:                            389
******* +Ldap Admin password:                  UNSET
        +Store ephemeral attributes outside Ldap: no
        +Secure interprocess communications:   yes
        +TimeZone:                             Africa/Monrovia
        +IP Mode:                              ipv4
        +Default SSL digest:                   sha256

   2) zimbra-mta:                              Enabled
        +Enable Spamassassin:                  yes
        +Enable Clam AV:                       yes
        +Enable OpenDKIM:                      yes
        +Notification address for AV alerts:   admin@mta-1.example.com
******* +Bind password for postfix ldap user:  UNSET
******* +Bind password for amavis ldap user:   UNSET

   3) zimbra-dnscache:                         Enabled
   s) Save config to file
   x) Expand menu
   q) Quit

Address unconfigured (**) items  (? - help)
....
--

4.  Type `1` to display the *Common Configuration* submenu.
+
--
[source%nowrap]
....
Common configuration

   1) Hostname:                                mta-1.example.com
** 2) Ldap master host:                        UNSET
   3) Ldap port:                               389
** 4) Ldap Admin password:                     UNSET
   5) Store ephemeral attributes outside Ldap: no
   6) Secure interprocess communications:      yes
   7) TimeZone:                                Africa/Monrovia
   8) IP Mode:                                 ipv4
   9) Default SSL digest:                      sha256
....

The mta server hostname is displayed.

[IMPORTANT]
You must change the LDAP master host name and password to be the
values configured on the LDAP server.

** Type `2`, press _Enter_, and type the LDAP host name.
   (*ldap-1.example.com* in this example.)
** Type `4`, press _Enter_, and type the LDAP password. +
   To obtain the LDAP password, you will need to log on to the
   LDAP server as the `zimbra` user, and run the following command:

[source%nowrap,bash]
....
zmlocalconfig -s zimbra_ldap_password
....

After you set these values, the server immediately contacts the LDAP
server. If it cannot contact the server, you cannot proceed.
--

5. Type `7` to set the correct time zone.
+
--
[source%nowrap]
....
1 Africa/Algiers
.
.
.
94 Europe/London
.
.
.
109 Pacific/Tongatapu
110 UTC
Enter the number for the local timezone: [110] 94
....
--


6. Type `r` to return to the *Main* menu.

7. Type `2` to got to the *Mta configuration* menu.
+
--
[source%nowrap]
....
Mta configuration

   1) Status:                                  Enabled
   2) Enable Spamassassin:                     yes
   3) Enable Clam AV:                          yes
   4) Enable OpenDKIM:                         yes
   5) Notification address for AV alerts:      admin@mta-1.example.com
** 6) Bind password for postfix ldap user:     UNSET
** 7) Bind password for amavis ldap user:      UNSET

Select, or 'r' for previous menu [r]
....
--

8.  You can change the `Notification address for AV alerts`.  This should be
    an address on the domain, such as the admin address. (*admin@example.com*)
+
--
[NOTE]
If you enter an address other than the admin address, you must provision an
account with that address after the installation is complete.
--

9.  Select the menu number for `Bind password for postfix ldap user`. +
    You must use the same value for this as is configured on the
    LDAP master server.

10.  Select the menu number for `Bind password for amavis ldap user`. +
     You must use the same value for this as is configured on the
     LDAP master server.

11. Type `r` to return to the *Main* menu.
+
--
[NOTE]
If you are installing the {product-short}-proxy package, see
<<_installing_zimbra_proxy>> before continuing.
--

12. When the MTA server is configured, return to the Main menu and
    type `a` to apply the configuration changes. +
    Press _Enter_ to save the configuration data.

13. When `Save configuration data to file` appears, +
    type `Yes` and press _Enter_.

14. The next request asks where to save the file.  To accept the default,
    press _Enter_. To save the files to another directory, enter the
    directory and then press _Enter_.

15. When `The system will be modified - continue?` appears, +
    type `Yes` and press _Enter_.
+
--
The server is modified. Installing all the components and configuring
the MTA server can take a few minutes. This can include setting
passwords, setting ports, setting time zone preferences, and starting
the server, among other processes.
--

16. When `Installation complete - press return to exit` displays,
    press _Enter_.

The installation of the MTA server is complete.

== Installing Zimbra Proxy

Installing the `zimbra-proxy` package is optional, but recommended for
scalable multi-server deployment. {product-short} proxy is normally installed
on the MTA server or can be configured on a separate server. {product-short}
proxy can be installed on more than one server. At least one instance
of `zimbra-memcached` must be installed to cache the route information
(upstream mailbox server for each endclient).

IMPORTANT: If you are moving from a non-proxy environment (for
example, single server to multi-server environment), additional steps
are necessary for the mailbox server and proxy configuration. After
you complete the proxy installation, reconfigure the mailbox server as
described in the {product-admin-guide}, _Zimbra Proxy_ chapter.

NOTE: Memcached is shipped as the caching layer to cache LDAP
lookups. Memcache does not have authentication and security features
so the servers should have a firewall set up appropriately. The
default port is `11211` and is controlled by the
`zimbraMemcacheBindPort` conf setting.


=== Installing on the MTA Server


If you are installing `zimbra-proxy` on the MTA server, select the
`zimbra-proxy` package and the `zimbra-memcached` package. Follow the
installation process for <<_installing_zimbra_mta_on_a_server>>.
After Step 11, configure the Zimbra-proxy.

. On the MTA server, select to install the `zimbra-proxy` and 
`zimbra-memcached` packages, type `y` and press *Enter* to install the selected
package.
. The _Main_ menu displays the default entries for the {product-short} component
you are installing. Select *Proxy Configuration* menu. You can modify
any of the values.
+
--
The *Bind password for Nginx ldap user* was configured when the LDAP
server was installed. This is set when the MTA connected to the LDAP
server. This is not used unless the Kerberos5 authenticating mechanism
is enabled.

NOTE: Setting the password even though GSSAPI auth/proxy
is not set up does not cause any issues.

----
Proxy configuration

      1) Status:                                Enabled
      2) Enable POP/IMAP Proxy:                 TRUE
      3) IMAP proxy port:                       143
      4) IMAP SSL proxy port:                   993
      5) POP proxy port:                        110
      6) POP SSL proxy port:                    995
      7) Bind password for nginx ldap user:     set
      8) Enable HTTP[S] Proxy:                  TRUE
      9) HTTP proxy port:                       80
      10) HTTPS proxy port:                     443
      11) Proxy server mode:                    https
----
--
+
Return to <<_installing_zimbra_mta_on_a_server>>, step 12,
to continue the MTA server installation.

=== Installing on a separate server

The LDAP host name and the {product-short} LDAP password must be known to the
proxy server. If not, the proxy server cannot contact the LDAP server
and the installation fails.

. Follow steps 1 through 4 in <<starting_multiple_server_install>>
to open a SSH session to the server, log on to the server as
root, and unpack the {product-short} software.
. Select to install the `zimbra-proxy` package and the `zimbra-memcached`
package. The other packages should be marked `N`. If you have not
installed `zimbra-proxy` on another server, you must have at least one
instance of `zimbra-memcached` installed to cache the data for NGINX, as
shown in the following screen shot example.
+
--
NOTE: If SNMP is used, the `zimbra-snmp` package must also be
installed.
--
+
--
[subs="quotes"]
----
Select the packages to install

Install zimbra-ldap [Y] N
Install zimbra-logger [Y] N
Install zimbra-mta [Y] N
Install zimbra-dnscache [N] N
Install zimbra-snmp [Y] N
Install zimbra-store [Y] N
Install zimbra-apache [Y] N
Install zimbra-spell [Y] N
Install zimbra-convertd [N] N
Install zimbra-memcached [N] *Y*
Install zimbra-proxy [N] *Y*
Install zimbra-archiving [N] N
Installing:
    zimbra-memcached
    zimbra-proxy

This system will be modified. Continue [N] *Y*
Configuration section
----
--
+
. Type `Y`, and press _Enter_ to install the selected package.
. The _Main_ menu displays. Type `1` and press _Enter_ to go to the *Common
Configuration* menu.
+
--
The mailbox server hostname is displayed. You must change the LDAP
master host name and password to be the values configured on the LDAP
server.

** Type `2`, press _Enter_, and type the LDAP host
   name. (`ldap-1.example.com`, in this example.)
** Type `4`, press _Enter_, and type the LDAP password.
+
After you set these values, the server immediately contacts the LDAP
server. If it cannot contact the server, you cannot proceed.
+
** Type 7 to set the correct time zone
--
+
. Type `r` to return to the Main menu.
. Type `2` to select `zimbra-proxy`.
+
--

----
Main menu

1) Common Configuration:
        +Hostname:                              localhost
        +Ldap master host:                      ldap-1.example.com
        +Ldap port:                             389
        +Ldap Admin password:                   set
        +Store ephemeral attributes outside Ldap: no
        +Secure interprocess communications:    yes
        +TimeZone:                              (GMT-08.00) Pacific Time (US & Canada)
        +IP Mode:                               ipv4      
        +Default SSL digest:                    sha256

2) zimbra-proxy:                              Enabled
        +Enable POP/IMAP Proxy:                 TRUE
        +IMAP server port:                      7143
        +IMAP server SSL port:                  7993
        +IMAP proxy port:                       143
        +IMAP SSL proxy port:                   993
        +POP server port:                       7110
        +POP server SSL port:                   7995
        +POP proxy port:                        110
        +POP SSL proxy port:                    995
******* +Bind password for nginx ldap user:     Not Verified
        +Enable HTTP[S] Proxy:                  TRUE
      	+Web server HTTP port:				  	8080
		+Web server HTTPS port:				  	8443
		+HTTP proxy port: 					  	80
		+HTTPS proxy port:					  	443
		+Proxy server mode:					  	https

3) Enable default backup schedule:			  	yes
s) Save config to file
x) Expand menu
q) Quit

Select, or 'r' for previous menu [r] 2

----

--
+
. The *Proxy Configuration* menu displays. You can modify any of the
values.
+
--
The *Bind password for Nginx ldap user* is configured when the LDAP
server was installed. This is set when the MTA connected to the LDAP
server. This is not used unless the Kerberos5 authenticating mechanism
is enabled.

NOTE: Setting the password even though GSSAPI auth/proxy is not set up
does not cause any issues.

----
Proxy configuration

   1) Status:                                  Enabled
   2) Enable POP/IMAP Proxy:                   TRUE
   3) IMAP server port:                        7143
   4) IMAP server SSL port:                    7993
   5) IMAP proxy port:                         143
   6) IMAP SSL proxy port:                     993
   7) POP server port:                         7110
   8) POP server SSL port:                     7995
   9) POP proxy port:                          110
  10) POP SSL proxy port:                      995
  11) Bind password for nginx ldap user:       set
  12) Enable HTTP[S] Proxy:                    TRUE
  13) Web server HTTP port:                    8080
  14) Web server HTTPS port:                   8443
  15) HTTP proxy port:                         80
  16) HTTPS proxy port:                        443
  17) Proxy server mode:                       https
----

--
+
. Type `r` to return to the _Main_ menu.
. When the proxy server is configured, return to the _Main_ menu and
type `a` to apply the configuration changes. Press _Enter_ to save the
configuration data.
. When *Save Configuration data to a file* appears, press _Enter_.
. The next request asks where to save the files. To accept the
default, press _Enter_. To save the files to another directory, enter
the directory and then press _Enter_.
. When *The system will be modified - continue?* appears, type `y` and
press _Enter_.
. When *Installation complete - press return to exit* displays, press
_Enter_.


The installation of the proxy server is complete.



== Installing zimbra-archiving Package


Installing the `zimbra-archiving` package is optional. This package
enables {product-name} Archiving and Discovery, which offers:

* Archiving, the ability to archive messages that were delivered to or
  sent by {product-abbrev}.
* Discovery, the ability to search across mailboxes.

The prerequisite to enabling archiving and discovery is the
installation and configuration of the `zimbra-archiving` package on at
least one mailbox server. The installation of this package provides
the {product-abbrev} discovery (also known as cross mailbox) search tool and sets
the attributes that allow archiving to be enabled on the {product-short} MTAs.

To enable archiving and discovery, select the `zimbra-store` and `zimbra-archiving`
packages during your installation process. The `zimbra-core`
package is installed by default.

[subs="quotes"]
----
Select the packages to install
Install zimbra-ldap [Y] N
Install zimbra-logger [Y] N
Install zimbra-mta [Y] N
Install zimbra-dnscache [N] N
Install zimbra-snmp [Y] N
Install zimbra-store [Y] *Y*
Install zimbra-apache [Y] N
Install zimbra-spell [Y] N
Install zimbra-convertd [N] N
Install zimbra-memcached [N] N
Install zimbra-proxy [N] N
Install zimbra-archiving [N] *Y*
Install zimbra-chat [Y] N
Install zimbra-drive [Y] N

Installing:
    zimbra-core
    zimbra-store
    zimbra-archiving
This system will be modified. Continue [N] *Y*
----


See the _Zimbra Archiving and Discovery_ chapter in the
{product-admin-guide} for more information about configuring and
archiving.


== Installing the zimbra-SNMP Package

Installing the `zimbra-snmp` package is optional, but if you use SNMP
monitoring, this package should be installed on each {product-short}
server.

In the _Main_ menu, select `zimbra-snmp` to make changes to the
default values. The following question is asked for SNMP configuration.

Configure whether to be notified by SNMP or SMTP. The default is
*No*. If you enter yes, you must enter additional information.

* For SNMP type the SNMP Trap host name.
* For SMTP type the SMTP source email address and destination email
  address.

----
8) zimbra-snmp:                             Enabled
   +Enable SNMP notifications:              yes
   +SNMP Trap hostname:                     example.com
   +Enable SMTP notifications:              yes
   +SMTP Source email address:              admin@example.com
   +SMTP Destination email address:         admin@example.com
----


== Final Set-Up

After the {product-short} servers are configured in a multi-node configuration,
the following functions must be configured:

* In order for remote management and postfix queue management, the ssh
  keys must be manually populated on each server. See
  <<_set_up_the_ssh_keys>>.
* If logger is installed, set up the syslog configuration files on
  each server to enable server statistics to display on the
  administration console, and then enable the logger monitor host. The
  server statistics includes information about the message count,
  message volume, and anti-spam and anti-virus activity. See
  <<_enabling_server_statistics_display>>.
* {product-name} ships a default `zimbra` user with a disabled
  password. {product-abbrev} requires access to this account via ssh public key
  authentication. On most operating systems this combination is okay,
  but if you have modified pam rules to disallow any ssh access to
  disabled accounts then you must define a password for the `zimbra`
  UNIX account. This will allow ssh key authentication for checking
  remote queues. See
  https://wiki.zimbra.com/wiki/Mail_Queue_Monitoring[Mail queue
  monitoring].
  

=== Set Up the SSH Keys

To populate the SSH keys, perform the following as the `zimbra`
user (`sudo su - zimbra`) on each server:

----
zmupdateauthkeys
----

The key is updated  in `/opt/zimbra/.ssh/authorized_keys`.

=== Enabling Server Statistics Display

In order for the server statistics to display on the administration
console, the syslog configuration files must be modified.

IMPORTANT: {product-name} supports the default syslog of a
supported operating system. Depending on your operating system, the
steps contained in this section might not be correct. See your
operating system documentation for specific information about how to
enable syslog.

. On each server, as `root`, type
`/opt/zimbra/libexec/zmsyslogsetup`. This enables the server to
display statistics.
. On the logger monitor host, you must enable either *syslog* or *rsyslog*
to log statistics from remote machines:
+
--

For *syslog*:

.. Edit the `/etc/sysconfig/syslog` file, add `-r` to the `SYSLOGD_OPTIONS`
setting, `SYSLOGD_options="-r -m 0"`.
.. Stop the syslog daemon. Type `/etc/init.d/syslog` stop.
.. Start the syslog daemon. Type `/etc/init.d/syslog start`.

For *syslog* on _Debian_ or _Ubuntu_:

.. Edit the `/etc/default/syslogd` file, add `-r` to the `SYSLOGD_OPTIONS`
setting, `SYSLOGD_options="-r -m 0"`
.. Stop the syslog daemon. Type `/etc/init.d/sysklogd stop`.
.. Start the syslog daemon. Type `/etc/init.d/sysklogd` start.

For *rsyslog*:

.. Uncomment the following lines in `/etc/rsyslog.conf`
+
----
$modload imudp
$UDPServerRun 514
----
+
.. Restart rsyslog

For *rsyslog* on _RHEL_ or _CentOS_:

.. Uncomment the following lines in `/etc/rsyslog.conf`.
+
----
# Provides UDP syslog reception
#$ModLoad imudp
#$UDPServerRun 514

# Provides TCP syslog reception
#$ModLoad imtcp
#$InputTCPServerRun 514
----

For *syslog-ng* on `SuSE`:

Uncomment the following from `/etc/syslog-ng/syslog-ng.conf`:

----
#
# uncomment to process log messages from network:
#
#udp(ip("0.0.0.0") port(514));
----

--
+


=== Spam/Ham Training on MTA servers

New installs of {product-abbrev} limit spam/ham training to the first MTA
installed. If you uninstall or move this MTA, you will need to enable
spam/ham training on another MTA, as one host should have this enabled
to run `zmtrainsa --cleanup`. To do this, set `zmlocalconfig -e
zmtrainsa_cleanup_host=TRUE`.


== Verifying Server Configuration

When *Configuration complete - press return to exit* is displayed, the
installation is finished and the server has been started. Before going
to the next server, you should verify that the server is running.


Use the CLI command, `zmcontrol status`, to verify that each server is
running.  Perform the following on each server in your {product-name}
environment.

. Log on as `root`.
. Type `su - zimbra`.
. Type `zmcontrol status`. The services status information is
displayed. All services should be running.
+
NOTE: If services are not started, you can type `zmcontrol start`. See
the CLI command appendix in the {product-admin-guide} for more
`zmcontrol` commands.


== Logging on to the Administration Console

. To log on to the administration console, open your browser, type the
administration console URL and log on to the console. The
administration console URL is entered as:
** In case of Mailbox servers containing backend mailstore and UI
services together (mailstore server + UI server), you can access the
admin console directly using
**\https://<mailstore-hostname>:<zimbraAdminPort>**.
The default value of `zimbraAdminPort` is `7071`.
** In case of a deployment having even a single mailbox server running
in Web Application server split mode, the admin console needs to be
accessed strictly through the proxy using
*\https://<proxy-hostname>:<zimbraAdminProxyPort>*
after switching `zimbraReverseProxyAdminEnabled` to `TRUE` and
restarting the proxy.
The default value of `zimbraAdminProxyPort` is `9071`.
+
[NOTE]
====
* The administration console address must be typed with `https`, even if you configured only `http`.
* The first time you log on, a certificate authority (CA) alert may be
displayed. Click *Accept this certificate permanently* to accept the
certificate and be able connect to the Zimbra administration console.
Then click *OK*.
====
+
. Enter the admin user name and password configured during the
installation process. Enter the user name as *admin@example.com*.


== Post Installation Tasks

Once {product-name} is installed, if you installed the
{product-short} license, you can log on to the administration console and
configure additional domains, create Classes of Service, and provision
accounts. See the {product-admin-guide}.

=== Defining Classes of Service

A default _Class of Service_ (COS) is automatically created during the
installation of {product-short} software. The COS controls mailbox quotas,
message lifetime, password restrictions, attachment blocking and
server pools. You can modify the default COS and create new COSs to
assign to accounts according to your group management policies.

In an environment with multiple mailbox servers, COS is used to assign
the new accounts to a mailbox server. The COS server pool page lists
the mailbox servers in your {product-short} environment. When you
configure the COS, select which servers to add to the server
pool. Within each pool of servers, a random algorithm assigns new
mailboxes to any available server.


To create or modify a COS, from the administration console,
click COS. If you have questions, refer to the Help section.

=== Provisioning Accounts

You can configure one account at a time with the New Account Wizard or
you can create many accounts at once using the Account Migration
Wizard.

==== Configuring One Account

The administration console _New Account Wizard_ steps you through the
account information to be completed.

. From the administration console Navigation pane, click *Accounts*.
+
NOTE: Four accounts are listed: admin account, two spam training
accounts, and a global Documents account. These accounts do not need
any additional configuration.
+
. Click *New*. The first page of the *New Account Wizard* opens.
. Enter the account name to be used as the email address and the last
name. This the only required information to create an account.
. You can click *Finish* at this point, and the account is configured with the
default COS and global features.
+
NOTE: To configure aliases, forwarding addresses, and specific features for this
account, proceed through the dialog before you click *Finish*.
+

When the accounts are provisioned, these accounts can immediately start to
send and receive emails.

==== Configuring Many Accounts at Once

You can provision multiple accounts at once using the _Account
Migration_ tool from the administration console. The wizard guides you
through the steps to import accounts from an external directory
server, either Active Directory or an LDAP server. The wizard
downloads account information from your directory and creates the
accounts in {product-abbrev}.

Refer to the {product-admin-guide} to learn more about provisioning accounts.

==== Import the Content of Users’ Mailboxes

{product-short}’s migration and import tools can be used to move users’ email
messages, calendars, and contacts from their old email servers to
their accounts on the Zimbra server. When the user’s files are
imported, the folder hierarchy is maintained. These tools can be
accessed from the administration console Download page and instruction
guides are available from the Administration Console Help Desk.


:leveloffset: +2
include::ephemeral.adoc[]
:leveloffset: -2


== Uninstalling Zimbra Collaboration

To uninstall servers, run the install script with the `-u` option.
Then delete the `/opt/zimbra` directory and remove the {product-abbrev} tgz file on the
servers.

. Change directories to the original install directory for the zcs
files.
. Type `./install.sh -u`.
. When *Completely remove existing installation?* is displayed, type
`Yes`.
+
====
The {product-short} servers are stopped, the existing packages, the webapp
directories, and the `/opt/zimbra` directory are removed.
====
+
. Delete the zcs directory, type `rm -rf [zcsfilename]`.
. Delete the `zcs.tgz` file, type `rm -rf zcs.tgz`.
. Additional files may need to be deleted. See
https://wiki.zimbra.com/wiki/UnInstalling_Zimbra_on_Linux[Uninstall Zimbra on Linux].

