[[multiple_server_install]]
= Multiple-Server Installation

The multiple-server installation is straight-forward and easy to run.
You run the same installation script on each server, select the
component(s) to install, and use the menu to configure the system.

When the server installation is complete after final set-up and server
configuration steps are run, the servers are started and the status is
displayed.

*Order of Installation*

1. {product-abbrev} LDAP server(s)
2. {product-abbrev} MTA server(s)
3. {product-abbrev} Proxy server(s)
4. {product-abbrev} Mailbox server(s) options:
    ** Zimbra Mailbox Server, which includes the mailstore services and
       webapp services (mailstore server + UI server)
    ** Zimbra Web Application Server Split mode, which includes:
        *** a Zimbra mailstore server (mailstore server)
        *** a Zimbra webapp server (UI server)

[NOTE]
Zimbra-proxy is normally installed on the MTA server or you can install it on its own server.

[IMPORTANT]
Do not manually create the user ‘zimbra’ before running the {product-abbrev}
installation. The installation automatically creates this user and sets up
its environment.

[IMPORTANT]
Before you start, verify that the system clocks are synced on all servers.

[[starting_multiple_server_install]]
== Starting the Installation Process

[IMPORTANT]
====
_Before you begin, make sure to:_

ifdef::networkeditiondoc[]
* Store your license in a directory folder on your server as it is needed to
  complete your installation of {product-name}. For more information about
  licenses, see <<Intro_license, {product-name} License>> and
  <<Zimbra_License_Requirements,Zimbra License Requirements>>
  ({product-edition-commercial} only)
endif::networkeditiondoc[]
* Confirm you have the latest system requirements and prerequisites for
  installing {product-name}, as described in
  <<System_Requirements, System Requirements for {product-name}>>
====

For the latest {product-name} software downloads, go to
https://www.zimbra.com. +
Save the {product-name} *tar* file to the computer from which you are
installing the software.

[NOTE]
_The screen shots are examples of the {product-name} installation
script. The actual script may be different._

Step 1 through step 4 are performed for each server to be installed.

Open an SSH session to the {product-short} server and follow the steps below:

1.  Log in as *root* to the {product-name} server and *cd* to the
    directory where the {product-name} archive file is saved
    (cd /var/<tmp>). Type the following commands.
+
--
    ** `tar xzvf [zcs.tgz]` to unpack the file
    ** `cd [zcs filename]` to change to the correct directory. The file
       name includes the release and build date.
    ** `./install.sh` to begin the installation.
--
+
--
[NOTE]
_As the installation proceeds, press_ *Enter* _to accept the
defaults that are shown in brackets_ [ ] _or enter the appropriate
answer for your configuration._

[source%nowrap,bash]
....
root@mailhost:/tmp# tar xzvf zcs.tgz
zcs-NETWORK-8.7.0_GA_1659.UBUNTU14_64.20160628202904/
zcs-NETWORK-8.7.0_GA_1659.UBUNTU14_64.20160628202904/packages/
zcs-NETWORK-8.7.0_GA_1659.UBUNTU14_64.20160628202904/packages/zimbra-apache_8.7.0.GA.1659.UBUNTU14.64_amd64.deb
.
.
.
zcs-NETWORK-8.7.0_GA_1659.UBUNTU14_64.20160628202904/install.sh
zcs-NETWORK-8.7.0_GA_1659.UBUNTU14_64.20160628202904/README.txt
root@zimbraiop:/tmp/# cd zcs-NETWORK-8.7.0_GA_1659.UBUNTU14_64.20160628202904/
root@zimbraiop:/tmp/zcs-NETWORK-8.7.0_GA_1659.UBUNTU14_64.20160628202904# ./install.sh

Operations logged to /tmp/install.log.y1YeCSI5
.
.
.
....
--

2. The *install.sh* script reviews the installation software to verify that the
   {product-short} packages are available. +
   The installation process checks to see whether any of the applications
   *Sendmail*, *Postfix*, *MySQL* or *MariaDB* are running. +
   If any of these applications are running, you are asked to disable them. +
   Disabling *MySQL* and *MariaDB* is *optional* but highly recommended. +
   *Sendmail* and *Postfix* *MUST* be disabled for {product-name} to start correctly.
+
--
[source%nowrap,bash]
....
root@zimbraiop:/tmp/zcs-NETWORK-8.7.0_GA_1659.UBUNTU14_64.20160628202904# ./install.sh

Operations logged to /tmp/install.log.y1YeCSI5
Checking for existing installation...
    zimbra-ldap...NOT FOUND
    zimbra-logger...NOT FOUND
    zimbra-mta...NOT FOUND
    zimbra-dnscache...NOT FOUND
    zimbra-snmp...NOT FOUND
    zimbra-store...NOT FOUND
    zimbra-apache...NOT FOUND
    zimbra-spell...NOT FOUND
    zimbra-convertd...NOT FOUND
    zimbra-memcached...NOT FOUND
    zimbra-proxy...NOT FOUND
    zimbra-archiving...NOT FOUND
    zimbra-core...NOT FOUND
.
.
.
....
--

3. The {product-short} software agreement displays. Read the agreement and when + 
`Do you agree with the terms of the software license agreement? [N]` + 
displays, enter `Y` to continue.
+
--
[IMPORTANT]
The license agreement displays in multiple sections,
and you must accept each section of the license agreement.
--


4. `Use {product-short}'s package repository [Y]` + 
displays, press `enter` to continue. Your system will be configured to add
the {product-short} packaging repository for *yum* or *apt-get* as appropriate
so it can install the {product-short} 3rd party packages.
+
--
[source%nowrap]
....
Checking for installable packages

Found zimbra-core
Found zimbra-ldap
Found zimbra-logger
Found zimbra-mta
Found zimbra-dnscache
Found zimbra-snmp
Found zimbra-store
Found zimbra-apache
Found zimbra-spell
Found zimbra-convertd
Found zimbra-memcached
Found zimbra-proxy
Found zimbra-archiving



Use Zimbra's package repository [Y] y
Configuring package repository
....
--

5. Next, select the packages to be installed on this server.
+
--
[NOTE]
For the cross mailbox search feature, install the {product-short} Archive
package. To use the archiving and discovery feature, contact {product-provider}
sales.
--
+
The installer verifies that there is enough room to install {product-short}.

6. Next, the installer checks to see that the prerequisite packages are
   installed as listed in the Other Dependencies section of the
   <<System_Requirements, System Requirements for {product-name}>>
+
--
[NOTE]
_Before the Main menu is displayed, the installer checks to see if the
hostname is resolvable via DNS and if there is an error asks
you if would like to change the hostname. The domain name should have an
MX record configured in DNS._
--

[[install_ldap_master]]
== Installing {product-short} LDAP Master Server

You must configure the {product-abbrev} LDAP Master server before you can install
other {product-abbrev} servers. You can set up LDAP replication, configuring a
master LDAP server and replica LDAP servers, either configuring all LDAP
servers now or after you set up the initial {product-name} servers. See the
section on <<ldap-replication,Configuring LDAP Replication>>

1. Follow steps 1 through 4 in
   <<starting_multiple_server_install,Starting the Installation Process>>
   to open an SSH session to the LDAP server, log on to the server as *root*,
   and unpack the {product-abbrev} software.
2. Type `y` and press `Enter` to install the `zimbra-ldap` package. +
   The `zimbra-mta`, `zimbra-store` and `zimbra-logger` packages should be
   marked `n`.
+
--
[source%nowrap]
....
Install zimbra-ldap [Y] y

Install zimbra-logger [Y] n

Install zimbra-mta [Y] n

Install zimbra-dnscache [Y] n

Install zimbra-snmp [Y] n

Install zimbra-store [Y] n

Install zimbra-apache [Y] n

Install zimbra-spell [Y] n

Install zimbra-convertd [Y] n

Install zimbra-memcached [Y] n

Install zimbra-proxy [Y] n

Install zimbra-archiving [N] n
Checking required space for zimbra-core

Installing:
    zimbra-core
    zimbra-ldap

The system will be modified.  Continue? [N]
....
--

3. Type `Y`, and press `Enter` to modify the system. The selected
   packages are installed on the server.
+
The Main menu displays the default entries for the Zimbra component you
are installing. +
To expand the menu to see the configuration values, type `x` and press `Enter`. +
The main menu expands to display configuration details for the package
being installed.
+
--
[NOTE]
Values that require further configuration are marked with asterisks (`*`).
--
+
To navigate the Main menu, select the menu item to change. You can
modify any of the values. See the section
<<main_menu_options,Main Menu options>>
for a description of the Main menu.
+
--
[source%nowrap]
....
Main menu

   1) Common Configuration:
   2) zimbra-ldap:                             Enabled
   3) Enable default backup schedule:          yes
   s) Save config to file
   x) Expand menu
   q) Quit

*** CONFIGURATION COMPLETE - press 'a' to apply
Select from menu, or press 'a' to apply config (? - help)
....
--

4.  Type `1` to display the *Common Configuration* submenu.
+
--
[source%nowrap]
....
Common configuration

   1) Hostname:                                ldap-1.example.com
   2) Ldap master host:                        ldap-1.example.com
   3) Ldap port:                               389
   4) Ldap Admin password:                     set
   5) Secure interprocess communications:      yes
   6) TimeZone:                                UTC
   7) IP Mode:                                 ipv4
   8) Default SSL digest:                      sha256

Select, or 'r' for previous menu [r]
....
--

5.  Type `4` to display the automatically generated LDAP admin password.
+
--
[source%nowrap]
....
Select, or 'r' for previous menu [r] 4

Password for ldap admin user (min 6 characters): [bEyMZxNxq]
....
--
+
--
You can change this password. +
Write down the LDAP password, the LDAP host name and the LDAP port.

[source%nowrap]
....
LDAP Admin Password _______________________
LDAP Host name      _______________________
LDAP Port           _______________________
....
--
[NOTE]
You must configure this information when you install the mailbox servers
and the MTA servers.

6. Type `6` to set the correct time zone.
+
--
[source%nowrap]
....
1 Africa/Algiers
.
.
.
94 Europe/London
.
.
.
109 Pacific/Tongatapu
110 UTC
Enter the number for the local timezone: [110] 94
....
--

7. Type `r` to return to the Main menu.

8.  From the Main menu, type `2` for *zimbra-ldap* to view the
    *Ldap configuration* settings.
+
--
[source%nowrap]
....
Ldap configuration

   1) Status:                                  Enabled
   2) Create Domain:                           yes
   3) Domain to create:                        ldap-1.example.com
   4) Ldap root password:                      set
   5) Ldap replication password:               set
   6) Ldap postfix password:                   set
   7) Ldap amavis password:                    set
   8) Ldap nginx password:                     set
   9) Ldap Bes Searcher password:              set

Select, or 'r' for previous menu [r]
....
--

9. Type `3` for *Domain to create* to change the default domain name to
   the main domain name you want to use for your network, (e.g. *example.com*).

10. The passwords listed in the *LDAP configuration* menu are automatically
    generated.
+
--
If you want to change the passwords for LDAP root, LDAP replication,
LDAP Postfix, LDAP Amavis, and LDAP Nginx, enter the
corresponding number `4` through `8` and change the passwords.

[source%nowrap]
....
Ldap replication password _____________________
Ldap postfix password     _____________________
Ldap amavis password      _____________________
Ldap nginx password       _____________________
....

[NOTE]
You need these passwords when configuring the MTA and the LDAP
replica servers. Write them down.
--

11. When changes to the LDAP configuration menu are complete:
+
--
[source%nowrap]
....
*** CONFIGURATION COMPLETE - press 'a' to apply
Select from menu, or press 'a' to apply config (? - help) a
Save configuration data to a file? [Yes]
Save config in file: [/opt/zimbra/config.8381]
Saving config in /opt/zimbra/config.8381...done
....
--

    ** enter `r` to return to the main menu.
    ** Type `a` to apply the configuration changes.
    ** When `Save configuration data to file` appears, +
       type `Yes` and press `Enter`.
    ** The next request asks where to save the files. +
       To accept the default, press `Enter`. +
       To save the files to another directory, enter the directory
       and press `Enter`.

12. When `The system will be modified - continue? [No]` appears, +
    type `y` and press `Enter`.
+
--
The server is modified. Installing all the components and configuring
the server can take a few minutes. This includes but is not limited to
setting local config values, creating and installing SSL certificates,
setting passwords, timezone preferences, and starting the servers, among
other processes.
--

13. When `Configuration complete - press return to exit` displays,
    press `Enter`.
+
--
[source%nowrap]
....
*** CONFIGURATION COMPLETE - press 'a' to apply
Select from menu, or press 'a' to apply config (? - help) a
Save configuration data to a file? [Yes]
Save config in file: [/opt/zimbra/config.8381]
Saving config in /opt/zimbra/config.8381...done.
The system will be modified - continue? [No] y
Operations logged to /tmp/zmsetup.20170302-133132.log
Setting local config values...done.
.
.
.
Starting servers...done.
Skipping creation of default domain GAL sync account - not a service node.
Setting up zimbra crontab...done.


Moving /tmp/zmsetup.20170302-133132.log to /opt/zimbra/log


Configuration complete - press return to exit
....

The installation of the LDAP server is complete.
--

[[install_mailbox]]
== Installing the {product-short} Mailbox Server

The *zimbra-store* package can be installed with the LDAP server, the MTA
server, or as a separate mailbox server.

You can have the following configuration options:

* The *{product-short} Mailbox Server* containing mailstore services and webapp
services (mailstore server + UI server)

or

* The *Zimbra Web Application Server Split*, which includes:

** Mailstore server providing the backend SOAP/REST functionality
** UI server providing the web UI functionality (static html/js/css content)

You can have more than one of the above configurations.
In a web application server split environment, you must have at least
one mailstore server and one UI server in your configuration.

[IMPORTANT]
A web application server split environment must have proxy and
memcached installed.

The Zimbra license file can be installed on one of the mailbox
servers during the installation.
If you do not have a license file, you can install it from the
administration console when the {product-name} install is complete.
See <<Zimbra_License_Requirements,Zimbra License Requirements>>

=== Install Zimbra Mailbox Services

1. Follow steps 1 through 4 in
   <<starting_multiple_server_install,Starting the Installation Process>>
   to open an SSH session to the Mailbox server, log on to the server as
   *root*, and unpack the {product-abbrev} software.

2. Type `y` and press `Enter` to install the *zimbra-logger* package
   (optional and only on one mail server) and *zimbra-store*.
   In the following screen shot example, the packages to be installed are emphasized.
+
--
[NOTE]
_If SNMP is being used, the SNMP package is installed on every
{product-short} server. Mark_ `y`

[source%nowrap]
....
Install zimbra-ldap [Y] n

Install zimbra-logger [Y] y

Install zimbra-mta [Y] n

Install zimbra-dnscache [N] n

Install zimbra-snmp [Y] y

Install zimbra-store [Y] y

Install zimbra-apache [Y] y

Install zimbra-spell [Y] y

Install zimbra-convertd [Y] y

Install zimbra-memcached [Y] n

Install zimbra-proxy [Y] n

Install zimbra-archiving [N] y
Checking required space for zimbra-core
Checking space for zimbra-store
Checking required packages for zimbra-store
     FOUND: libreoffice-1:4.2.8-0ubuntu4
zimbra-store package check complete.

Installing:
    zimbra-core
    zimbra-logger
    zimbra-snmp
    zimbra-store
    zimbra-apache
    zimbra-spell
    zimbra-convertd
    zimbra-archiving

The system will be modified.  Continue? [N]
....
--

3. Type `Y`, and press `Enter` to modify the system. The selected
   packages are installed on the server.
+
The Main menu displays the default entries for the Zimbra component you
are installing. +
To expand the menu to see the configuration values, type `x` and press `Enter`. +
The main menu expands to display configuration details for the package
being installed.
+
--
[NOTE]
Values that require further configuration are marked with asterisks (`*`).
--
+
To navigate the Main menu, select the menu item to change. You can
modify any of the values. See the section
<<main_menu_options,Main Menu options>>
for a description of the Main menu.
+
--
[source%nowrap]
....
Main menu

   1) Common Configuration:
        +Hostname:                             mailstore-1.example.com
******* +Ldap master host:                     UNSET
        +Ldap port:                            389
******* +Ldap Admin password:                  UNSET
        +LDAP Base DN:                         cn=zimbra
        +Secure interprocess communications:   yes
        +TimeZone:                             UTC
        +IP Mode:                              ipv4
        +Default SSL digest:                   sha256

   2) zimbra-logger:                           Enabled
   3) zimbra-snmp:                             Enabled
   4) zimbra-store:                            Enabled
        +Create Admin User:                    yes
        +Admin user to create:                 admin@mailstore-1.example.com
******* +Admin Password                        UNSET
        +Anti-virus quarantine user:           virus-quarantine.orulkdewtz@mailstore-1.example.com
        +Enable automated spam training:       yes
        +Spam training user:                   spam.udbnonsavi@mailstore-1.example.com
        +Non-spam(Ham) training user:          ham.3ptgqja0f@mailstore-1.example.com
******* +SMTP host:                            UNSET
        +Web server HTTP port:                 8080
        +Web server HTTPS port:                8443
        +HTTP proxy port:                      80
        +HTTPS proxy port:                     443
        +Web server mode:                      https
        +IMAP server port:                     7143
        +IMAP server SSL port:                 7993
        +IMAP proxy port:                      143
        +IMAP SSL proxy port:                  993
        +POP server port:                      7110
        +POP server SSL port:                  7995
        +POP proxy port:                       110
        +POP SSL proxy port:                   995
        +Use spell check server:               yes
        +Spell server URL:                     http://mailstore-1.example.com:7780/aspell.php
        +Configure for use with mail proxy:    TRUE
        +Configure for use with web proxy:     TRUE
        +Enable version update checks:         TRUE
        +Enable version update notifications:  TRUE
        +Version update notification email:    admin@mailstore-1.example.com
        +Version update source email:          admin@mailstore-1.example.com
        +Install mailstore (service webapp):   yes
        +Install UI (zimbra,zimbraAdmin webapps): yes
******* +License filename:                     UNSET

   5) zimbra-spell:                            Enabled
   6) zimbra-convertd:                         Enabled
   7) Default Class of Service Configuration:
   8) Enable default backup schedule:          yes
   s) Save config to file
   x) Expand menu
   q) Quit

Address unconfigured (**) items  (? - help)
....
--

4.  Type `1` to display the *Common Configuration* submenu.
+
--
[source%nowrap]
....
Common configuration

   1) Hostname:                                mailstore-1.example.com
** 2) Ldap master host:                        UNSET
   3) Ldap port:                               389
** 4) Ldap Admin password:                     UNSET
   5) LDAP Base DN:                            cn=zimbra
   6) Secure interprocess communications:      yes
   7) TimeZone:                                UTC
   8) IP Mode:                                 ipv4
   9) Default SSL digest:                      sha256
....

The mailbox server hostname is displayed.

[IMPORTANT]
You must change the LDAP master host name and password to be the
values configured on the LDAP server.

** Type `2`, press `Enter`, and type the LDAP host name.
   (*ldap-1.example.com* in this example.)
** Type `4`, press `Enter`, and type the LDAP password. +
   To obtain the LDAP password, you will need to log on to the
   LDAP server as the `zimbra` user, and run the following command:

[source%nowrap,bash]
....
zmlocalconfig -s zimbra_ldap_password
....

After you set these values, the server immediately contacts the LDAP
server. If it cannot contact the server, you cannot proceed.
--

5. Type `7` to set the correct time zone.
+
--
[source%nowrap]
....
1 Africa/Algiers
.
.
.
94 Europe/London
.
.
.
109 Pacific/Tongatapu
110 UTC
Enter the number for the local timezone: [110] 94
....
--

6. Type `r` to return to the Main menu.

7.  From the Main menu, type `4` for *zimbra-store* to view the
    *Store configuration* settings.
+
--
[source%nowrap]
....
Store configuration

   1) Status:                                  Enabled
   2) Create Admin User:                       yes
   3) Admin user to create:                    admin@mailstore-1.example.com
** 4) Admin Password                           UNSET
   5) Anti-virus quarantine user:              virus-quarantine.orulkdewtz@mailstore-1.example.com
   6) Enable automated spam training:          yes
   7) Spam training user:                      spam.udbnonsavi@mailstore-1.example.com
   8) Non-spam(Ham) training user:             ham.3ptgqja0f@mailstore-1.example.com
** 9) SMTP host:                               UNSET
  10) Web server HTTP port:                    8080
  11) Web server HTTPS port:                   8443
  12) HTTP proxy port:                         80
  13) HTTPS proxy port:                        443
  14) Web server mode:                         https
  15) IMAP server port:                        7143
  16) IMAP server SSL port:                    7993
  17) IMAP proxy port:                         143
  18) IMAP SSL proxy port:                     993
  19) POP server port:                         7110
  20) POP server SSL port:                     7995
  21) POP proxy port:                          110
  22) POP SSL proxy port:                      995
  23) Use spell check server:                  yes
  24) Spell server URL:                        http://mailstore-1.example.com:7780/aspell.php
  25) Configure for use with mail proxy:       TRUE
  26) Configure for use with web proxy:        TRUE
  27) Enable version update checks:            TRUE
  28) Enable version update notifications:     TRUE
  29) Version update notification email:       admin@mailstore-1.example.com
  30) Version update source email:             admin@mailstore-1.example.com
  31) Install mailstore (service webapp):      yes
  32) Install UI (zimbra,zimbraAdmin webapps): yes
**33) License filename:                        UNSET

Select, or 'r' for previous menu [r]
....
--

8. Type `4` and set the password for the administrator account.
   The password is case sensitive and must be a minimum of six
   characters.  During the install process, the admin account is
   provisioned on the mailbox store server. You log on to the
   administration console with this password.
+
--
[NOTE]
_By default, the domain name portions of the email addresses for the
Admin user, Anti-virus quarantine user, Spam training user and Non-spam(Ham)
training user, are set to be the zimbra mailstore server address.
You may want to change these to be the {product-name} primary domain address
instead.  (*example.com* in this example)_
--

9. Type the corresponding number to set the `SMTP host`.  This is the
   mta-server host name.

10. Type the corresponding number if you want to change the default
    `Web server mode`. The communication protocol options are
    HTTP, HTTPS, mixed, both or redirect.
+
--
** *Mixed* mode uses HTTPS for logging in and HTTP for normal session
   traffic
** *Both* mode means that an HTTP session stays HTTP, including during
   the login phase, and an HTTPS session remains HTTPS throughout,
   including the login phase.
** *Redirect* mode redirects any users connecting via HTTP to an HTTPS
   connection.

All modes use SSL encryption for back-end administrative traffic.
--

11. If you are configuring proxy servers, type the corresponding number
    to enable the servers. When you enable these, the mail server port
    and proxy port numbers are automatically changed.
// TODO add link in here
    See the Planning for the Installation chapter, Configuring Proxy Server.

12. If you install the *{product-short}-spell* package, it should be installed
    on every mailstore. +
    The hostname portion of the http address for each should be the hostname
    of the mailstore server it is installed on.

13. `Enable version update checks` and `Enable version update notifications`
    are set to TRUE. {product-name} automatically checks for the latest
    {product-name} software updates and notifies the account that is
    configured in Version update notification email.
    You can modify this later from the administration console.

14. If the *{product-short}-proxy* package is not installed on the mailbox
    server, two menu options are displayed so you can preconfigure the
    mailbox server for use with the zimbra proxy server:
+
--
** Configure for use with mail proxy
** Configure for use with web proxy

Set either or both of these to TRUE if you are going to set up
{product-short}-proxy. +
The {product-short}-proxy ports display in the menu when these are set
to TRUE.
--

15. *({product-edition-commercial} only)*.  Type the corresponding menu
    number to install the Zimbra license file. +
    Enter the location of the Zimbra license file. For example, if you
    saved the license file to the tmp directory,
    you would type `/tmp/ZCSLicense.xml`. +
    You cannot proceed without a license.

16. Configure the mailstore and webapp services either on a single
    server or in a split server configuration.
+
--
** To install mailstore server only, set
  `Install UI (zimbra,zimbraAdmin webapps)` value to `no`,
   which will exclude the web services.
** To install UI server only, set the
   `Install mailstore (service webapp)` value to `no`,
   which will exclude mailstore services.
** To install both the mailstore and UI services on the same server,
   confirm the values for +
   `Install mailstore (service webapp)` and +
   `Install UI (zimbra,zimbraAdmin webapps)` +
   are both set to `yes`.  The default is `yes`.

[NOTE]
See the release notes for additional configuration information
for installing a split node environment.
--

17. Type `r` to return to the Main menu.

18. Review the Default Class of Service Configuration settings.
    If you want to change the COS default configuration of
    these features, type the number for the
    `Default Class of Service Configuration` Then type the
    corresponding number for the feature to be enabled or disabled. +
    The default COS settings are adjusted to match.

19.  When the mailbox server is configured, return to the Main menu
     and type `a` to apply the configuration changes. +
     Press `Enter` to save the configuration data.

20. When Save Configuration data to file appears, type `Yes` and press `Enter`.
+
--
....
Save configuration data to a file? [Yes]
....
--

21. The next request asks where to save the files. To accept the
default, press `Enter`. To save the files to another directory, enter the
directory and then press Enter
+
--
....
Save config in file: [/opt/zimbra/config.16039]
Saving config in /opt/zimbra/config.16039...done.
....
--

22. When `The system will be modified - continue?` appears, type `Yes` and
press `Enter`.
+
The server is modified. Installing all the components and configuring
the server can take several minutes. This includes installing SSL
certificates, setting passwords, setting ports, installing skins
and common zimlets, setting time zone preferences, backup schedules
and starting the servers, among other processes.
+
--
....
The system will be modified - continue? [No] y
Operations logged to /tmp/zmsetup.20160711-234517.log
Setting local config values...done.
.
.
.
Configuration complete - press return to exit
....
--

23. When `Configuration complete - press return to exit` displays,
    press `Enter`

The installation of the mailbox server is complete.
