[[Zimbra-Network-NG-Modules-first-steps-guide]]
= Zimbra Network NG Modules: First Steps

This Guide contains all information needed to switch to the new Zimbra Network NG modules from their legacy counterparts after upgrading to Zimbra 8.8.

[[backup-ng]]
Switching to Backup NG
----------------------
Switching to the new Backup NG is a simple process that will initialize the
new backup system on a dedicated path.
Until the initialization is completed, the old backup engine will be active.
Old backup files will not be removed and the old backup and restore tools are
still available via the usual CLI commands.

[[backup-path-limitations]]
Backup Path Limitations
~~~~~~~~~~~~~~~~~~~~~~~
To hold Backup NG data, a storage must comply to the following:

* The storage must have a mountpoint on the system.
** The "zimbra" user must of course have r/w permission on the path.
* The data must be stored on a case-sensitive filesystem.

TIP: Backup NG features a built-in scheduling system and does not rely on the system's cron service. At the end of the initialisation process, old backup-related crontab lines will be automatically removed.

[[backup-ng-initialisation]]
Backup NG Initialization
~~~~~~~~~~~~~~~~~~~~~~~~
Before initializing the Backup NG module, make sure you have enough space on
the storage where you will store the backup. The average size of the backup is
50-70% of the nominal total quota of all mailboxes.

*To initialize the Backup NG module:*

* Access the Zimbra Administration Console.
* Enter the "Network Modules NG" section on the left menu.
* Enter the "Backup" section.
* Set the "Backup Path" to the directory where you will store your backup.
* Click the "Initialize" button - this will trigger a SmartScan to initialize the Backup Path

[[mobile-ng]]
Switching to Mobile NG
----------------------
Switching to the new Mobile NG is a simple process that will activate the new
mobile handlers and deactivate the old ones. This will also switch the synchronization control
over to Mobile NG from the legacy Zimbra Mobile.
Until the initialization is complete, the old mobile engine will be active.

[[what-happens-after-the-switch]]
What Happens after the Switch
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
After switching to Mobile NG, all existing syncstates will be invalidated,
and all connected devices will automatically re-synchronise all of their data
through the new engine.

WARNING: *Since the switch will force all connected devices to re-synchonise all
of their data, make sure to alert your users beforehand to make sure that they have
wifi coverage or enough traffic on their mobile data plans.
 +
 +
Furthermore, the switch might lead to an abrupt increase in the number of connections to the server, and consequently its load, due to the resynchronisation of all devices.*

The switch is completely transparent to end users, and no user interaction
 should be prompted or required, but being the Exchange ActiveSync protocol mostly client-driven different behaviours might be experienced, such as:

* Device not synchronising until user's action (e.g. opening the email client).
* Device requiring a restart.
* Device not synchronising until the user re-enters their username and password in the account's settings.

_Albeit sporadic, such behaviours and the load impact on the system should be taken into account when planning to switch to Mobile NG._

[[mobile-ng-initialisation]]
Mobile NG Initialization
~~~~~~~~~~~~~~~~~~~~~~~~

*To initialize Mobile NG:*

* Access the Zimbra Administration Console.
* Enter the "Network Modules NG" section on the left menu.
* Enter the "Mobile" section.
* Click the "Activate" button.

[[hsm-ng]]
Switching to HSM NG
-------------------
The HSM NG module will become active as soon as the upgrade to Zimbra 8.8 is
complete, and does not require any interaction.

Any old HSM policy, volume and volume configuration will be maintained.

TIP: HSM NG features a built-in scheduling system and does not rely on the system's cron service. At the first start after the upgrade, old HSM-related crontab lines will be automatically removed.


[[admin-ng]]
Switching to Admin NG
---------------------
Switching to the new Admin NG is a simple process that will migrate any
relevant ACL information to the module's own configuration manager, clearing
existing ACLs and ACEs from the system.

Admin NG is significantly different than the old Delegated Administration engine.
Please read the product's documentation and only migrate to Admin NG if its feature set
meets your needs.

WARNING: *Switching to Admin NG will remove all existing ACLs and ACEs from the server. This new module is extremely different from its legacy counterpart, so after the migration will not be able to recreate the very same admin roles and settings.* +
 +
*_This is a one way only process._* +
 +
*Once Admin NG is initialized
it's not possible to go back to the old engine, so if you have customized or complex
ACLs/ACEs carefully consider whether or not to switch.*

[[admin-ng-initialisation]]
Admin NG Initialization
~~~~~~~~~~~~~~~~~~~~~~~
Admin NG is not enabled by default during upgrades from a version earlier than 8.8, so it must be enabled manually before migrating to it.

*To enable Admin NG:*

* Run the following command as the "zimbra" user on any mailbox server:

  zmprov mcf zimbraNetworkAdminNGEnabled TRUE


*To initialize Admin NG:*

* Access the Zimbra Administration Console.
* Enter the "Network Modules NG" section on the left menu.
* Enter the "Admin" section.
* Click on the "Migrate" button.
