[[Overview_of_Installation_Process]]
= Overview of the Installation Process
:toc:

When you run the install script, the process verifies that the correct
prerequisite Zimbra application packages are available to be installed.

[[Zimbra_Application_Packages]]
== Zimbra Application Packages

Zimbra architecture includes open-source integrations using industry
standard protocols. The third-party software has been tested and
configured to work with the Zimbra software.

The following describes the Zimbra packages that are installed.

* *Zimbra Core:* This package includes the libraries, utilities,
monitoring tools, and basic configuration files. Zimbra Core is
automatically installed on each server.

* *Zimbra Store:* The Zimbra store includes the components for the
mailbox server, including Jetty, which is the servlet container the
Zimbra software runs within. The Zimbra mailbox server includes the
following components:
** Data store: The data store is a MariaDB© database.
** Message store: The message store is where all email messages and file
attachments reside.
** Index store: Index and search technology is provided through Lucene.
Index files are maintained for each mailbox.
** Web application services: The Jetty web application server runs web
applications (webapps) on any store server. It provides one or more web
application services.

* **Zimbra LDAP:**User authentication is provided through OpenLDAP®
software. Each account on the Zimbra server has a unique mailbox ID that
is the primary point of reference to identify the account. The OpenLDAP
schema has been customized for {product-name}. The Zimbra LDAP
server must be configured before the other servers. You can set up LDAP
replication, configuring a master LDAP server and replica LDAP servers.

* *Zimbra MTA:* Postfix is the open source mail transfer agent (MTA)
that receives email via SMTP and routes each message to the appropriate
Zimbra mailbox server using Local Mail Transfer Protocol (LMTP). The
Zimbra MTA also includes the anti-virus and anti-spam components.

* *Zimbra Proxy:* Zimbra Proxy is a high-performance reverse proxy
service for passing IMAP[S]/POP[S]/HTTP[S] client requests to other
internal {product-name} services.This package is normally installed on the MTA
server(s) or on its own independent server(s). When the zimbra-proxy
package is installed, the proxy feature is enabled by default.
Installing the Zimbra Proxy is highly recommended, and required if using
a separate web application server.

* *Zimbra Memcached:* Memcached is automatically selected when the
zimbra-proxy is installed. At least one server must run zimbra-memcached
when the proxy is in use. You can use a single memcached server with one
or more Zimbra proxies.

* *Zimbra SNMP:* Installing the Zimbra SNMP package is optional. If you
choose to install zimbra-SNMP for monitoring, this package should be
installed on every Zimbra server.

* *Zimbra Logger:* Installing the Zimbra Logger package is optional and
is installed on one mailbox server. The Zimbra Logger installs tools for
syslog aggregation and reporting. If you do not install Logger, the
server statistics section of the administration console will not
display. *Note:* The Logger package must be installed at the same time
as the mailbox server.

* *Zimbra Spell:* Installing the Zimbra Spell package is optional.
Aspell is the open source spell checker used on the Zimbra Web Client.

* *Zimbra Apache:* This package is installed automatically when Zimbra
Spell or Zimbra Convertd is installed.

The Zimbra server configuration is menu driven. The installation menu
shows you the default configuration values. The menu displays the
logical host name and email domain name [mailhost.example.com] as
configured on the computer. You can change any of the values. For single
server installs, you must define the administrator’s password, which you
use to log on to the administration console, and you specify the
location of the Zimbra license xml file.

[[Downloading_the_Zimbra_Software]]
= Downloading the Zimbra Software

Obtain the {product-name} software download and save to the
computer from which you will install the software.
