[[Overview_of_Installation_Process]]
= Overview of the Installation Process
:toc:

When you run the install script, the process verifies that the correct
prerequisite Zimbra application packages are available to be installed.

[[Zimbra_Application_Packages]]
== {product-short} Application Packages

{product-short} architecture includes open-source integrations using industry
standard protocols. The third-party software has been tested and
configured to work with the {product-short} software.

The following describes the Zimbra packages that are installed.

* *{product-short} Core:* This package includes the libraries, utilities,
monitoring tools, and basic configuration files. {product-short} Core is
automatically installed on each server.

* *{product-short} Store:* The {product-short} store includes the components for the
mailbox server, including Jetty, which is the servlet container the
{product-short} software runs within. The {product-short} mailbox server includes the
following components:
** Data store: The data store is a MariaDB© database.
** Message store: The message store is where all email messages and file
attachments reside.
** Index store: Index and search technology is provided through Lucene.
Index files are maintained for each mailbox.
** Web application services: The Jetty web application server runs web
applications (webapps) on any store server. It provides one or more web
application services.

* *{product-short} LDAP:* User authentication is provided through OpenLDAP®
software. Each account on the Zimbra server has a unique mailbox ID that
is the primary point of reference to identify the account. The OpenLDAP
schema has been customized for {product-name}. The {product-short} LDAP
server must be configured before the other servers. You can set up LDAP
replication, configuring a master LDAP server and replica LDAP servers.

* *{product-short} MTA:* Postfix is the open source mail transfer agent (MTA)
that receives email via SMTP and routes each message to the appropriate
{product-short} mailbox server using Local Mail Transfer Protocol (LMTP). The
{product-short} MTA also includes the anti-virus and anti-spam components.

* *{product-short} Proxy:* {product-short} Proxy is a high-performance reverse proxy
service for passing IMAP[S]/POP[S]/HTTP[S] client requests to other
internal {product-name} services.This package is normally installed on the MTA
server(s) or on its own independent server(s). When the `zimbra-proxy`
package is installed, the proxy feature is enabled by default.
Installing the {product-short} Proxy is required as of
{product-abbrev} 8.7.


* *{product-short} Memcached:* Memcached is automatically selected when the
`zimbra-proxy` is installed. At least one server must run `zimbra-memcached`
when the proxy is in use. You can use a single memcached server with one
or more {product-short} proxies.

* *{product-short} SNMP:* Installing the {product-short} SNMP package is optional. If you
choose to install `zimbra-snmp` for monitoring, this package should be
installed on every {product-short} server.

* *{product-short} Logger:* Installing the {product-short} Logger package is optional and
is installed on one mailbox server. The {product-short} Logger installs tools for
syslog aggregation and reporting. If you do not install Logger, the
server statistics section of the administration console will not
display.
+
NOTE: The Logger package must be installed at the same time
as the mailbox server.
+

* *{product-short} Spell:* Installing the {product-short} Spell package is optional.
Aspell is the open source spell checker used on the {product-short} Web Client.

* *{product-short} Apache:* This package is installed automatically when {product-short}
Spell or {product-short} Convertd is installed.

The {product-short} server configuration is menu driven. The installation menu
shows you the default configuration values. The menu displays the
logical host name and email domain name [mailhost.example.com] as
configured on the computer. You can change any of the values. For single
server installs, you must define the administrator’s password, which you
use to log on to the administration console, and you specify the
location of the {product-short} license xml file.

[[Downloading_the_Zimbra_Software]]
= Downloading the {product-short} Software

Obtain the {product-name} software download and save to the
computer from which you will install the software.
