[[Zimbra_Application_Packages]]
== {product-short} Application Packages

{product-short} architecture includes open-source integrations using industry
standard protocols. The third-party software has been tested and
configured to work with the {product-short} software.

The following describes the {product-name} application packages that are
installed.

* *{product-short} Core:* This package includes the libraries, utilities,
monitoring tools, and basic configuration files. {product-short} Core is
automatically installed on each server.

* *{product-short} LDAP:* User authentication is provided through `OpenLDAP®`
software. Each account on the Zimbra server has a unique mailbox ID that
is the primary point of reference to identify the account. The OpenLDAP
schema has been customized for {product-name}.
+
[NOTE]
The {product-short} LDAP server must be configured before any other servers.
+
You can set up LDAP replication, configuring a master LDAP server and
replica LDAP servers.

* *{product-short} Store:* This package includes the components for the
*mailbox server*, including *Jetty*, which is the servlet container the
{product-short} software runs within. The {product-short} *mailbox server* includes the
following components:

** *Data store:* The data store is a `MariaDB©` database.
** *Message store:* The message store is where all email messages and
   file attachments reside.
** *Index store:*  Index and search technology is provided through `Lucene`.
   Index files are maintained for each mailbox.
** *Web application services:* The `Jetty` web application server runs
web applications (webapps) on any store server. It provides one or more
web application services.

* *{product-short} MTA:* `Postfix` is the open source mail transfer agent (MTA)
that receives email via SMTP and routes each message to the appropriate
{product-short} mailbox server using Local Mail Transfer Protocol (LMTP). The
{product-short} MTA also includes *anti-virus* and *anti-spam* components.

* *{product-short} Proxy:* {product-short} Proxy is a high-performance reverse proxy
service for passing IMAP[S]/POP[S]/HTTP[S] client requests to other
internal {product-name} services using `nginx`.  This package is normally
installed on the MTA server(s) or on its own independent server(s). When
the *zimbra-proxy* package is installed, the proxy feature is enabled by
default.
+
[NOTE]
Installing the {product-short} Proxy is required as of
{product-abbrev} 8.7.

[NOTE]
By default {product-short} Proxy is configured to perform strict server name enforcement of the HTTP 'Host' header sent by clients for new installs.  Strict server name enforcement may be disabled during the
post-install configuration process in the {product-short} Proxy
configuration section or using the `zimbraReverseProxyStrictServerNameEnabled` configuration
option. Please see the {product-short} Proxy section of the administration guide for more details.

ifdef::z9[]
* *{product-short} {modern}:* This package includes the assets of {product-short} {modern}. This package is automatically installed on each server.
endif::z9[]

* *{product-short} Memcached:* This package is automatically selected when the
*{product-short}-Proxy* package is installed and provides access to `Memcached`.
+
[NOTE]
At least one server must run *zimbra-memcached* when the {product-short} Proxy
service is in use.
+
You can use a single memcached server with one or more {product-short} proxies.

* *{product-short} SNMP:* Installing this package is optional.
+
[NOTE]
If you choose to install *{product-short}-SNMP* for monitoring, this package
should be installed on every {product-short} server.

* *{product-short} Logger:* Installing this package is optional. It
is installed on one mailbox server. It provides tools for `syslog`
aggregation and reporting.
+
[NOTE]
====
* If you do not install *{product-short} Logger*, the server statistics section of
the administration console will not display.
* The *{product-short} Logger* package must be installed at the same time as the
*{product-short} Store* package.
====

* *{product-short} Spell:* This package is optional.  It provides the open source
spell checker `Aspell` used by the {product-short} Web Client.

ifdef::z9[]
* *{product-short} Spell:* This package is optional.  It provides the open source
spell checker `Aspell` used by the {product-short} {web-client}.
endif::z9[]

* *{product-short} Apache:* This package is installed automatically when *{product-short}
Spell*
ifdef::networkeditiondoc[]
or *{product-short} Convertd*
endif::networkeditiondoc[]
is installed.

* *{product-short} Convertd:* This package should be installed on at least one
*{product-short}-Store* server. Only one *{product-short}-Convertd* package needs to be
present in the {product-name} environment. The default is to install one
*{product-short}-Convertd* on each *{product-short}-Store* server.

ifdef::networkeditiondoc[]
* *{product-short} Archiving:* The {product-short} Archiving and Discovery feature is an
optional feature for {product-name} *{product-edition-commercial}*. +
Archiving and Discovery offers the ability to store and search all messages
that were delivered to or sent by {product-name}. +
This package includes the *cross mailbox search* function which can be
used for both live and archive mailbox searches.
+
[WARNING]
Using Archiving and Discovery can trigger additional mailbox
license usage. To find out more about {product-short} Archiving and Discovery,
please refer to {product-short} Admin Guide.
endif::networkeditiondoc[]

ifndef::z9[]
* *{product-short} Connect:* Installing this package is optional. This package should be installed on at least one *{product-short}-Store* server. {product-short} Connect includes a server extension with all
the necessary modules to run an embedded XMPP Server, and an End-User Zimlet which connects
to the server extension and offer to the users a rich point-to-point text-chat conversations.
{product-short} Connect is marked as GA and supported starting {product-name} 8.8.
+

[NOTE]
The {product-short} Connect package must be selected and installed on every *{product-short}-Store*.

* *{product-short} Drive:* Installing this package is optional.This package should be installed on at least one
*{product-short}-Store* server. {product-short} Drive includes a server extension with all
the necessary modules to connect and authenticate {product-short} users against a ownCloud or
NextCloud Server, and an End-User Zimlet which allow users to perform actions to the their docu-
ments stored on ownCloud or Nextcloud.
{product-short} Drive is marked as GA and supported starting {product-name} 8.8.
+
[NOTE]
The {product-short} Drive package must be selected and installed on every *{product-short}-Store*.
+

[WARNING]
Zimbra Drive only provides connectivity to a ownCloud or NextCloud Server. It is the Customer's
responsibility to maintain, backup, and protect the data stored on ownCloud or NextCloud Servers.
endif::z9[]

The {product-short} server configuration is menu driven. The installation menu
shows you the default configuration values. The menu displays the
logical host name and email domain name [mailhost.example.com] as
configured on the computer. You can change any of the values. For single
server installs, you must define the administrator’s password, which you
use to log on to the administration console, and you specify the
location of the {product-short} license xml file.
