[[Zimbra_Application_Packages]]
== Zimbra Application Packages

The {product-name} architecture includes open-source integrations
using industry standard protocols. The third-party software has
been tested and configured to work with the {product-name} software.

The following describes the {product-name} application packages that are
installed.

* **Zimbra Core:** This package includes the libraries, utilities,
monitoring tools, and basic configuration files. **Zimbra Core** is
automatically installed on each server.

* **Zimbra LDAP:** User authentication is provided through `OpenLDAP®`
software. Each account on the Zimbra server has a unique mailbox ID that
is the primary point of reference to identify the account. The OpenLDAP
schema has been customized for {product-name}.
+
[NOTE]
The Zimbra LDAP server must be configured before any other servers.
+
You can set up LDAP replication, configuring a master LDAP server and
replica LDAP servers.

* **Zimbra Store:** This package includes the components for the
**mailbox server**, including **Jetty**, which is the servlet container the
Zimbra software runs within. The Zimbra **mailbox server** includes the
following components:

** **Data store:** The data store is a `MariaDB©` database.
** **Message store:** The message store is where all email messages and
   file attachments reside.
** **Index store:**  Index and search technology is provided through `Lucene`.
   Index files are maintained for each mailbox.
** **Web application services:** The `Jetty` web application server runs
web applications (webapps) on any store server. It provides one or more
web application services.

* **Zimbra MTA:** `Postfix` is the open source mail transfer agent (MTA)
that receives email via SMTP and routes each message to the appropriate
Zimbra mailbox server using Local Mail Transfer Protocol (LMTP). The
Zimbra MTA also includes **anti-virus** and **anti-spam** components.

* **Zimbra Proxy:** Zimbra Proxy is a high-performance reverse proxy
service for passing IMAP[S]/POP[S]/HTTP[S] client requests to other
internal {product-name} services using `nginx`.  This package is normally
installed on the MTA server(s) or on its own independent server(s). When
the **zimbra-proxy** package is installed, the proxy feature is enabled by
default.
+
[NOTE]
Installing the Zimbra Proxy is highly recommended, and is required when
using a separate web application server.

* **Zimbra Memcached:** This package is automatically selected when the
**Zimbra-Proxy** package is installed and provides access to `Memcached`.
+
[NOTE]
At least one server must run **zimbra-memcached** when the Zimbra Proxy
service is in use.
+
You can use a single memcached server with one or more Zimbra proxies.

* **Zimbra SNMP:** Installing this package is optional.
+
[NOTE]
If you choose to install **Zimbra-SNMP** for monitoring, this package
should be installed on every Zimbra server.

* **Zimbra Logger:** Installing this package is optional. It
is installed on one mailbox server. It provides tools for `syslog`
aggregation and reporting.
+
[NOTE]
====
* If you do not install **Zimbra Logger**, the server statistics section of
the administration console will not display.
* The **Zimbra Logger** package must be installed at the same time as the
**Zimbra Store** package.
====

* **Zimbra Spell:** This package is optional.  It provides the open source
spell checker `Aspell` used by the Zimbra Web Client.

* **Zimbra Apache:** This package is installed automatically when **Zimbra
Spell** or **Zimbra Convertd** is installed.

* **Zimbra Convertd:** This package should be installed on at least one
**Zimbra-Store** server. Only one **Zimbra-Convertd** package needs to be
present in the {product-name} environment. The default is to install one
**Zimbra-Convertd** on each **Zimbra-Store** server.

ifdef::networkeditiondoc[]
* **Zimbra Archiving:** The Zimbra Archiving and Discovery feature is an
optional feature for {product-name} **Network Edition**. +
Archiving and Discovery offers the ability to store and search all messages
that were delivered to or sent by {product-name}. +
This package includes the **cross mailbox search** function which can be
used for both live and archive mailbox searches.
+
[WARNING]
Using Archiving and Discovery can trigger additional mailbox
license usage. To find out more about Zimbra Archiving and Discovery,
contact Zimbra sales.
endif::networkeditiondoc[]
