[[System_Requirements]]
= System Requirements for {product-name}
:toc:

[cols="20,80a",grid="all"]
|===
|*Servers*
|*Evaluation and Testing*

* Intel/AMD 64-bit CPU 1.5 GHz
* RAM requirements:
** For single server installations, a minimum of 8GB of RAM is required.
** For multi-server installations, contact {product-provider} sales for recommendations.
* 5 GB free disk space for software and logs
* Temp file space for installs and upgrades*
* Additional disk space for mail storage

*Production environments*

* Intel/AMD 2.0 GHZ+ 64-bit CPU
* RAM requirements:
** For single server installations, a minimum of 8GB of RAM is required.
** For multi-server installations, contact {product-provider} sales for recommendations.
* Temp file space for installs and upgrades*
* 10 GB free disk space for software and logs (SATA or SCSI for
performance, and RAID/Mirroring for redundancy)
* Additional disk space for mail storage
* Temp files space: The zimbra-store requires 5GB for `/opt/zimbra`, plus
additional space for mail storage. The other nodes require 100MB.

*General Requirements*

* Firewall Configuration should be set to “No firewall”.
* RAID-5 is not recommended for installations with more than 100 accounts.
|*Network Edition and Open Source supported Cloud platforms*
|The following Cloud Platforms are supported:

* Oracle Cloud
* VMware vCloud Director
* VMware vCloud Air

|*Operating System ({product-edition-commercial})*
|The following operating systems are supported:

* Red Hat® Enterprise Linux® 7 (64-bit)
* CentOS Linux® 7 (64-bit)
* Red Hat Enterprise Linux 6 (64-bit), *patch level 4 or later is required*
* CentOS Linux 6 (64-bit), *patch level 4 or later is required*
* Oracle Linux 7.2
* Oracle Linux 6.6
* Ubuntu 16.04 LTS Server Edition (64-bit), starting from Zimbra Collaboration 8.7.1 and above
* Ubuntu 14.04 LTS Server Edition (64-bit)
* Ubuntu 12.04.4 LTS Server Edition (64-bit) *running the saucy (3.11) or
later kernel is required. Deprecated starting Zimbra Collaboration 8.8*. 
+
[NOTE]
If the original install was done with
Ubuntu 12.04.2 or earlier, manual intervention is required to switch to
the saucy (3.11) or later kernel series.
See https://wiki.ubuntu.com/Kernel/LTSEnablementStack for further information.

|*Operating System (Open Source Edition)*
|In addition to supporting the operating systems listed above for the
{product-edition-commercial}, other operating system versions are available for the
{product-edition-foss}. Check the {product-provider} Open Source Downloads page on
https://www.zimbra.com.

|*Virtualization ({product-edition-commercial})*
|The following hypervisors are supported:

* VMware vSphere 5.x
* VMware vSphere 4.x
* XenServer 6.5
* XenServer 6.2
* KVM

|*File Systems*
|The following file systems are supported:

* *XFS*
* *ext3* or *ext4* file systems for Linux deployments
* *NFS* for backup only

|*Other Dependencies*
|Netcat (nc) is required on all operating systems using {product-name}.
The `nc` utility must be installed prior to installation or upgrading.

For SUSE and Ubuntu systems, disable *AppArmor* and verify that the
AppArmor service is not running before installing {product-name}.

For Red Hat Enterprise, Fedora Core and SUSE operating systems, the
server must also have the following installed:

* **NPTL**. Native POSIX Thread Library
* **Sudo**. Superuser, required to delegate admins.
* **libidn**. For internationalizing domain names in applications (IDNA)
* **GMP**. GNU Multiple-Precision Library.

For Ubuntu 14 and Ubuntu 12:

* Sudo
* libidn11
* libpcre3
* libexpat1
* libgmp3c2

|*Miscellaneous*
|* SSH client software to transfer and install the {product-name} software.
* Valid DNS configured with an A record and MX record.
* Servers should be configured to run Network Time Protocol (NTP) on a scheduled basis.

a|Administrator Computers +
 +
[NOTE]
 Other configurations may work.
|The following operating system/browser combinations are supported:

// TODO this looks well out of date.  How about Windows 10?  Edge browser?
Windows XP with required updates, Vista, Windows 7, or Windows 8 with
one of the following:

* Internet Explorer 8.0 and higher
** IE8.x for XP
** IE9.x and higher for Vista/Windows 7
** IE10 and higher for Windows 8
* The latest stable release of:
** Firefox
** Safari
** Google Chrome

Mac OS X 10.5, 10.6, 10.7, or 10.8 with one of the following:

* The latest stable release of:
** Firefox
** Safari
** Google Chrome

Linux (Red Hat, Ubuntu, Fedora, or SUSE) with one of the following:

* The latest stable release of:
** Firefox
** Google Chrome

|*Administrator Console Monitor*
|Display minimum resolution 1024 x 768

a|*End User Computers using {product-short} Web Client* +
 +
[NOTE]
 Other configurations may work.
|*For {product-short} Web Client - Advanced & Standard version*

Minimum

* Intel/AMD/Power PC CPU 750MHz
* 256MB RAM

Recommended

* Intel/AMD/Power PC CPU 1.5GHz
* 512MB RAM

The following operating system/browser combinations are supported:

Windows XP with required updates, Vista, Windows 7, Windows 8 or Windows 10 with one of the following:

* Internet Explorer 8.0 and higher
** IE8.x for XP
** IE9.x and higher for Vista/Windows 7
** IE10 and higher for Windows 8
* Microsoft Edge, supported since ZCS 8.6 P4 and above
* The latest stable release of:
** Firefox
** Safari
** Google Chrome

// TODO El Capitan is 10.11 and that isn't even the latest...
Mac OS X 10.5, 10.6, 10.7, or 10.8 with one of the following:

* The latest stable release of:
** Firefox
** Safari
** Google Chrome

Linux (Red Hat, Ubuntu, Fedora, or SUSE) with one of the following:

* The latest stable release of:
** Firefox
** Google Chrome

|*End User Computers Using Other Clients*
|Minimum

* Intel/AMD/Power PC CPU 750MHz
* 256MB RAM

Recommended

* Intel/AMD/Power PC CPU 1.5GHz
* 512MB RAM

Operating system POP/IMAP combinations

* Windows XP SP 3, Vista SP 2, Windows 7 with Outlook Express 6, Outlook
2003, (MAPI), Thunderbird
* Fedora Core 4 or later with Thunderbird
* Mac OS X 10.4 or later with Apple Mail

*Accessibility and Screen Readers* {product-provider} recommends that customers
requiring use of screen readers for accessibility leverage the use of
the Standard {product-short} Web Client (HTML). {product-provider} continues to invest in
improving the accessibility of this interface.

[TIP]
If users are presently using IE 6, {product-provider} strongly recommends that they upgrade
to the latest version of Internet Explorer for optimal performance with ZWC.

|*Exchange Web Services*
|EWS Clients

* Outlook 2011 (MAC only)
* Apple Desktop Clients (OS X, 10.8+)

EWS Interoperability

* Exchange 2007+

|*Monitor*
|Display minimum resolution: 1024 x 768

|*Internet Connection Speed*
|128 kbps or higher
|===

ifdef::networkeditiondoc[]
[[Zimbra_Connector_for_Outlook]]
== {product-short} Connector for Outlook ({product-edition-commercial} Only)

[width="100%",cols="20%,80%",]
|=======================================================================
|*Operating System* a|
* Windows 10
* Windows 8
* Windows 7
* Vista
* Windows XP with required updates
+
[IMPORTANT]
Windows XP is deprecated. The 8.x series of Zimbra Collaboration is the last release to support
Microsoft Outlook 2003 and Microsoft Windows XP

|*Microsoft Outlook* a|
* Outlook 2016: 32-bit and 64-bit editions of Microsoft Outlook are supported.
* Outlook 2013: 32-bit and 64-bit editions of Microsoft Outlook are supported.
* Outlook 2010: 32-bit and 64-bit editions of Microsoft Outlook are supported.
* Outlook 2007: Client computers must have Microsoft Office Outlook 2007
SP3 or later installed.
* Outlook 2003: Client computers must have Microsoft Office Outlook 2003 SP3 or later installed.
+
[IMPORTANT]
Outlook 2003 is deprecated. The 8.x series of Zimbra Collaboration is the last release to
support Microsoft Outlook 2003 and Microsoft Windows XP.
|=======================================================================
endif::networkeditiondoc[]

ifdef::networkeditiondoc[]
[[Zimbra_Mobile]]
== {product-short} Mobile ({product-edition-commercial} Only)

'''

{product-edition-commercial} Mobile (MobileSync) provides mobile data access to email,
calendar, and contacts for users of selected mobile operating systems,
including:

*Smartphone Operating Systems*:

* iOS6, iOS7, iOS8, iOS9
* Android 2.3 and above
* Windows Mobile 6.0 and above
* Microsoft Outlook using the Exchange ActiveSync (EAS)

[[Zimbra_Touch_Client]]
== {product-short} Touch Client ({product-edition-commercial} Only)

'''

Supported devices for the {product-short} Touch Client include:

* iOS6+: iPad®, iPad mini®, iPhone®, iPod touch®
* Android 4.0+: Nexus 7, Nexus 10, Samsung Galaxy Tab™,
  Samsung Galaxy S® III, Samsung Galaxy S® 4, Galaxy Nexus™
endif::networkeditiondoc[]

ifdef::networkeditiondoc[]
[[BES]]
== Zimbra Connector for BlackBerry Enterprise Server ({product-edition-commercial} Only)

{product-provider} Connector for BlackBerry Enterprise Server (ZCB) provides seamless,
real-time synchronization of Zimbra user mailbox data to BlackBerry devices.

See https://www.zimbra.com/products/blackberry-enterprise-server.html for more information.
endif::networkeditiondoc[]

[[Available_Languages]]
== Available Languages

This section includes information about available languages, including
<<end_user_translations,End User Translations>> and
<<admin_translations,Administrator Translations>>.

[[end_user_translations]]
=== End User Translations

[cols="15,15,70",]
|=======================================================================
|*Component* |*Category* |*Languages*

|{product-short} Web Client |Application/UI |Arabic, Basque (EU), Chinese
(Simplified PRC and Traditional HK), Danish, Dutch, English (AU, UK,
US), French, French Canadian, German, Hindi, Hungarian, Italian,
Japanese, Korean, Malay, Polish, Portuguese (Brazil), Portuguese
(Portugal), Romanian, Russian, Spanish, Swedish, Thai, Turkish,
Ukrainian

|{product-short} Web Client - Online Help (HTML) |Feature Documentation |Dutch,
English, Spanish, French, Italian, Japanese, German, Portuguese
(Brazil), Chinese (Simplified PRC and Traditional HK), Russian

|{product-short} Web Client - End User Guide (PDF) |Feature Documentation
|English

|{product-short} Connector for Microsoft Outlook |Installer + Application/UI
|Arabic, Basque (EU), Chinese (Simplified PRC and Traditional HK),
Danish, Dutch, English (AU, UK, US), French, French Canadian, German,
Hindi, Hungarian, Italian, Japanese, Korean, Malay, Polish, Portuguese
(Brazil), Portuguese (Portugal), Romanian, Russian, Spanish, Swedish,
Thai, Turkish, Ukrainian

|{product-short} Connector for Microsoft Outlook - End User Guide (PDF) |Feature
Documentation |English
|=======================================================================

[[admin_translations]]
=== Administrator Translations

[cols="15,15,70",]
|=======================================================================
|*Component* |*Category* |*Languages*
|{product-short} Admin Console |Application |Arabic, Basque (EU), Chinese
(Simplified PRC and Traditional HK), Danish, Dutch, English (AU, UK,
US), French, French Canadian, German, Hindi, Hungarian, Italian,
Japanese, Korean, Malay, Polish, Portuguese (Brazil), Portuguese
(Portugal), Romanian, Russian, Spanish, Swedish, Turkish, Ukrainian

|{product-short} Admin Console Online Help (HTML) |Feature Documentation |English

|"Documentation" Install + Upgrade / Admin Manual / Migration / Import /
Release Notes / System Requirements |Guides |English

|{product-short} Connector for Microsoft Outlook - Admin Guide (PDF) |
Install + Configuration Guide |English
|=======================================================================

Note: To find SSH client software, go to Download.com at
http://www.download.com/ and search for SSH. The list displays software
that can be purchased or downloaded for free. An example of a free SSH
client software is PuTTY, a software implementation of SSH for Win32 and
Unix platforms. To download a copy go to http://putty.nl/[http://putty.nl]
