[[System_Requirements]]
= System Requirements for {product-name}
:toc:

[cols="20,80a",grid="all"]
|===
|*Servers*
|*Evaluation and Testing*

* Intel/AMD 64-bit CPU 1.5 GHz
* RAM requirements:
** For single server installations, {product-short} requires a minimum of 8GB of RAM.
** For multi-server installations, contact {product-provider} sales for recommendations.
* 5 GB free disk space for software and logs
* Temp file space for installs and upgrades*
* Additional disk space for mail storage

*Production environments*

* Intel/AMD 2.0 GHZ+ 64-bit CPU
* RAM requirements:
** For single server installations, {product-short} requires a minimum of 8GB of RAM.
** For multi-server installations, contact {product-provider} sales for recommendations.
* Temp file space for installs and upgrades*
* 10 GB free disk space for software and logs (SATA or SCSI for
performance, and RAID/Mirroring for redundancy)
* Additional disk space for mail storage
* Temp files space: The zimbra-store requires 5GB for `/opt/zimbra`, plus
additional space for mail storage. The other nodes require 100MB.

*General Requirements*

* Set the firewall configuration to *No firewall*.
* We do not recommend RAID-5 for installations with more than 100 accounts.
|*Network Edition and Open Source supported Cloud platforms*
|The following Cloud Platforms are supported:

* Oracle Cloud
* VMware vCloud Director
* VMware vCloud Air

|*Operating System ({product-edition-commercial})*
|The following operating systems are supported:

* Red Hat® Enterprise Linux® 7 (64-bit)
* CentOS Linux® 7 (64-bit)
* Red Hat Enterprise Linux 6 (64-bit), *patch level 4 or later is required*
* CentOS Linux 6 (64-bit), *patch level 4 or later is required*
* Oracle Linux 7.2
* Oracle Linux 6.6
* Ubuntu 16.04 LTS Server Edition (64-bit), starting from Zimbra Collaboration 8.7.1 and above
* Ubuntu 18.04 LTS Server Edition (64-bit), starting from Zimbra Collaboration 8.8.12 and above (Beta)
+

ifndef::z9[]
|*Operating System (Open Source Edition)*
|In addition to supporting the operating systems listed above for the
{product-edition-commercial}, other operating system versions are available for the
{product-edition-foss}. Check the {product-provider} Open Source Downloads page on
https://www.zimbra.com.
endif::z9[]

|*Virtualization ({product-edition-commercial})*
|The following hypervisors are supported:

* VMware vSphere 6.x
* VMware vSphere 5.x
* VMware vSphere 4.x
* XenServer 6.5
* XenServer 6.2
* KVM

|*File Systems*
|The following file systems are supported:

* *XFS*
* *ext3* or *ext4* file systems for Linux deployments
* *NFS* for backup only

|*Other Dependencies*
|Netcat (`nc`) is required on all operating systems using {product-name}.
Install the `nc` utility before installation or upgrading.

For SUSE and Ubuntu systems, disable *AppArmor* and verify that the
AppArmor service is not running before installing {product-name}.

For Red Hat Enterprise, Fedora Core and SUSE operating systems, the
server must also have the following installed:

* **NPTL**. Native POSIX Thread Library
* **Sudo**. Superuser, required to delegate admins.
* **libidn**. For internationalizing domain names in applications (IDNA)
* **GMP**. GNU Multiple-Precision Library.

For Ubuntu 16 and 18:

* Sudo
* libidn11
* libpcre3
* libexpat1
* libgmp3c2

|*Miscellaneous*
|* SSH client software to transfer and install the {product-name} software.
* Valid DNS configured with an A record and MX record.
* Servers should be configured to run Network Time Protocol (NTP) on a scheduled basis.

a|*Administrator Computers* +
 +
// HACK because including a NOTE in a narrow table column causes problems for
// the prawn layout engine for PDFs.
ifdef::backend-pdf[]
NOTE: Other configurations may work.
endif::[]
ifndef::backend-pdf[]
[NOTE]
Other configurations may work.
endif::[]
|The following operating system/browser combinations are supported:

Windows 7 SP1, Windows 8.1or Windows 10 with
one of the following:

* Microsoft support is only available for Internet Explorer 11 or Microsoft Edge
** IE11 and higher for Windows 7 SP1
** IE11 and higher for Windows 8.1
** IE11 or Microsoft Edge for Windows 10
* The latest stable release of:
** Firefox
** Safari
** Google Chrome

IMPORTANT: IE11 is not supported when using {product-short} Connect. {product-short} Connect requires webRTC support which IE doesn't provide yet. 

MacOS 10.12 or 10.13, 10.14 with one of the following:

* The latest stable release of:
** Firefox
** Safari
** Google Chrome

Linux (Red Hat, Ubuntu, Fedora, or SUSE) with one of the following:

* The latest stable release of:
** Firefox
** Google Chrome

|*Administrator Console Monitor*
|Display minimum resolution 1024 x 768

a|*End User Computers using {product-short} Web Client* +
 +
// HACK because including a NOTE in a narrow table column causes problems for
// the prawn layout engine for PDFs.
ifdef::backend-pdf[]
NOTE: Other configurations may work.
endif::[]
ifndef::backend-pdf[]
[NOTE]
Other configurations may work.
endif::[]

ifndef::z9[]
|*For {product-short} Web Client - Advanced & Standard version*
endif::z9[]

ifdef::z9[]
|*For {product-short} Web Client - Classic & Modern version*
endif::z9[]

Minimum

* Intel/AMD/Power PC CPU 750MHz
* 256MB RAM

Recommended

* Intel/AMD/Power PC CPU 1.5GHz
* 512MB RAM

The following operating system/browser combinations are supported:

ifndef::z9[]
Windows 7 SP1, Windows 8.1 or Windows 10 with
one of the following:

* Microsoft support is only available for Internet Explorer 11 or Microsoft Edge
** IE11 and higher for Windows 7 SP1
** IE11 and higher for Windows 8.1
** IE11 or Microsoft Edge for Windows 10

* The latest stable release of:
** Firefox
** Safari
** Google Chrome

IMPORTANT: IE11 is not supported when using {product-short} Connect. {product-short} Connect requires webRTC support which IE doesn't provide yet. 

MacOS 10.12 or 10.13, 10.14 with one of the following:
* The latest stable release of:
** Firefox
** Safari
** Google Chrome

Linux (Red Hat, Ubuntu, Fedora, or SUSE) with one of the following:

* The latest stable release of:
** Firefox
** Google Chrome
endif::z9[]

ifdef::z9[]
Windows 8.1 or Windows 10 with the latest stable release of one of the following:

** Google Chrome
** Firefox
** Microsoft Edge

MacOS 10.13 or newer with the latest stable release of one of the following:

** Google Chrome
** Firefox
** Safari

Linux (Red Hat, Ubuntu, Fedora, or SUSE) with the latest stable release of one of the following:

** Google Chrome
** Firefox

a|*Mobile Devices using {product-short} Web Client* +
 +

|{product-short} {product-version} supports mobile web browsers using the *{modern} only*. 

The following operating system/browser combinations are supported:

Apple-supported iPhone and iPad models with their latest iOS version and with the latest stable release of one of the following:

** Safari
** Chrome
** Firefox

Phones or tablets running an up-to-date version of Android still supported by Google with the latest stable release of one of the following:

** Android Browser
** Chrome
** Firefox
endif::z9[]

|*End User Computers Using Other Clients*
|Minimum

* Intel/AMD/Power PC CPU 750MHz
* 256MB RAM

Recommended

* Intel/AMD/Power PC CPU 1.5GHz
* 512MB RAM

Operating system POP/IMAP combinations

* Windows 7 SP1 with Outlook Express 6, Outlook
2007 and above (MAPI), Thunderbird
* Fedora Core 4 or later with Thunderbird
* Mac OS X 10.6 or later with Apple Mail

*Accessibility and Screen Readers* {product-provider} recommends that customers
requiring the use of screen readers for accessibility leverage the use of
the Standard {product-short} Web Client (HTML). {product-provider} continues to invest in
improving the accessibility of this interface.

[TIP]
If users are presently using IE 10 or older {product-provider} strongly recommends that they upgrade to the latest version of Internet Explorer for optimal performance with ZWC.

|*Exchange Web Services*
|EWS Clients

* Outlook 2011/2016 (MAC only)
* Apple Desktop Clients (macOS 10.12+)

EWS Interoperability

* Exchange 2010+

|*Monitor*
|Display minimum resolution: 1024 x 768

|*Internet Connection Speed*
|128 kbps or higher
|===

ifdef::networkeditiondoc[]
[[Zimbra_Connector_for_Outlook]]
== {product-short} Connector for Outlook ({product-edition-commercial} Only)

[width="100%",cols="20%,80%",]
|=======================================================================
|*Operating System* a|
* Windows 10
* Windows 8.1

ifndef::z9[]
* Windows 7 SP1
+
[IMPORTANT]
Windows 7 SP1 is in its Extended Support period until January 14, 2020. {product-name} 8.8.x
is the last release to support Microsoft Outlook 2010 and Microsoft Windows 7 SP1.
endif::z9[]

|*Microsoft Outlook* a|
* Outlook 2019: 32-bit and 64-bit editions of Microsoft Office (new in 8.8.11), including Click to run.
* Outlook 2016: 32-bit and 64-bit editions of Microsoft Office, including Office365 (New in 8.8.10) and Click to run versions.
* Outlook 2013: 32-bit and 64-bit editions of Microsoft Office.
* Outlook 2010: 32-bit and 64-bit editions of Microsoft Office (End of life: October 13, 2020.)

|=======================================================================
endif::networkeditiondoc[]

ifdef::networkeditiondoc[]
ifndef::z9[]
[[Zimbra_Mobile]]
== {product-short} Mobile ({product-edition-commercial} Only)

{product-edition-commercial} Mobile (MobileSync) provides mobile data access to email,
calendar, and contacts for users of selected mobile operating systems,
including:

*Smartphone Operating Systems*:

* iOS9, iOS10, iOS11
* Android 2.3 and above
* Windows Mobile 6.0 and above
* Microsoft Outlook using Exchange ActiveSync (EAS)

[[Zimbra_Touch_Client]]
== {product-short} Touch Client ({product-edition-commercial} Only)

IMPORTANT: Support for the {product-short} Touch Client has ended.
The software is available without support.

Supported devices for the {product-short} Touch Client include:

* iOS9+: iPad®, iPad mini®, iPhone®, iPod touch®
* Android 4.0+: Nexus 7, Nexus 10, Samsung Galaxy Tab™,
  Samsung Galaxy S® III, Samsung Galaxy S® 4, Galaxy Nexus™
endif::z9[]
endif::networkeditiondoc[]

[[Available_Languages]]
== Available Languages

This section includes information about available languages, including
<<end_user_translations,End User Translations>> and
<<admin_translations,Administrator Translations>>.

[[end_user_translations]]
=== End User Translations

[cols="15,15,70",]
|=======================================================================
|*Component* |*Category* |*Languages*

|{product-short} {web-client} |Application/UI |Arabic, Basque (EU), Chinese
(Simplified PRC and Traditional HK), Danish, Dutch, English (AU, UK,
US), French, French Canadian, German, Hindi, Hungarian, Italian,
Japanese, Korean, Malay, Polish, Portuguese (Brazil), Portuguese
(Portugal), Romanian, Russian, Spanish, Swedish, Thai, Turkish,
Ukrainian

ifdef::z9[]
|{product-short} {modern} |Application/UI |Chinese
(China), English (US), French (France), German, 
Hindi, Indonesian, Italian,
Japanese, Portuguese (Portugal), Spanish, Thai 
endif::z9[]

|{product-short} {web-client} - Online Help (HTML) |Feature Documentation |Dutch,
English, Spanish, French, Italian, Japanese, German, Portuguese
(Brazil), Chinese (Simplified PRC and Traditional HK), Russian

ifdef::z9[]
|{product-short} {modern} - Online End User Guide (HTML) |Feature Documentation |
English
endif::z9[]

|{product-short} {web-client} - End User Guide (PDF) |Feature Documentation
|English

|{product-short} Connector for Microsoft Outlook |Installer + Application/UI
|Arabic, Basque (EU), Chinese (Simplified PRC and Traditional HK),
Danish, Dutch, English (AU, UK, US), French, French Canadian, German,
Hindi, Hungarian, Italian, Japanese, Korean, Malay, Polish, Portuguese
(Brazil), Portuguese (Portugal), Romanian, Russian, Spanish, Swedish,
Thai, Turkish, Ukrainian

|{product-short} Connector for Microsoft Outlook - End User Guide (PDF) |Feature
Documentation |English
|=======================================================================

[[admin_translations]]
=== Administrator Translations

[cols="15,15,70",]
|=======================================================================
|*Component* |*Category* |*Languages*
|{product-short} Admin Console |Application |Arabic, Basque (EU), Chinese
(Simplified PRC and Traditional HK), Danish, Dutch, English (AU, UK,
US), French, French Canadian, German, Hindi, Hungarian, Italian,
Japanese, Korean, Malay, Polish, Portuguese (Brazil), Portuguese
(Portugal), Romanian, Russian, Spanish, Swedish, Turkish, Ukrainian

|{product-short} Admin Console Online Help (HTML) |Feature Documentation |English

|"Documentation" Install + Upgrade / Admin Manual / Migration / Import /
Release Notes / System Requirements |Guides |English

|{product-short} Connector for Microsoft Outlook - Admin Guide (PDF) |
Install + Configuration Guide |English
|=======================================================================

Note: To find SSH client software, go to Download.com at
http://www.download.com/, and search for SSH. The list displays software
that can be purchased or downloaded for free. An example of a free SSH
client software is PuTTY, a software implementation of SSH for Win32 and
Unix platforms. To download a copy go to http://putty.nl/[http://putty.nl]
