[[System_Requirements]]
= System Requirements for {product-name}
:toc:

[cols="20,80a",grid="all"]
|===
|*Servers*
|*Evaluation and Testing*

* Intel/AMD w/ PassMark CPU Mark > 7,500 (e.g., Intel Xeon E-224G @ 3.5GHz = 9,913)
* RAM requirements:
** For single server installations, {product-short} requires a minimum of 8GB of RAM.
** For multi-server installations, contact {product-provider} sales for recommendations.
* 50 GB free disk space for software and logs
* Temp file space for installs and upgrades*
* Additional disk space for mail storage

*Production environments*

* Intel/AMD w/ PassMark CPU Mark > 15,000 (e.g., AMD EPYC 7401P @ 2.0GHz = 18,199)
* RAM requirements:
** For single server installations, {product-short} requires a minimum of 8GB of RAM.
** For multi-server installations, contact {product-provider} sales for recommendations.
* Temp file space for installs and upgrades*
* 100 GB free disk space for software and logs (SATA or SCSI for
performance, and RAID/Mirroring for redundancy)
* Additional disk space for mail storage
* Temp files space: The zimbra-store requires 5GB for `/opt/zimbra`, plus
additional space for mail storage. The other nodes require 100MB.

*General Requirements*

* Set the firewall configuration to *No firewall*.
* We do not recommend RAID-5 for installations with more than 100 accounts.
|*Cloud platforms*
|The following Cloud Platforms are supported:

* Oracle Cloud
* VMware vCloud Director
* VMware vCloud Air

|*Operating System*
|The following operating systems are supported:

* Red Hat® Enterprise Linux® 8 (64-bit)
* CentOS Linux® 8 (64-bit)
* Red Hat® Enterprise Linux® 7 (64-bit)
* CentOS Linux® 7 (64-bit)
* Red Hat Enterprise Linux 6 (64-bit), *patch level 4 or later is required*
* CentOS Linux 6 (64-bit), *patch level 4 or later is required*
* Oracle Linux 7.2
* Oracle Linux 6.6
* Ubuntu 16.04 LTS Server Edition (64-bit)
* Ubuntu 18.04 LTS Server Edition (64-bit), starting from Zimbra Collaboration 8.8.12 and above
+

|*Virtualization*
|The following hypervisors are supported:

* VMware vSphere 6.5 or 6.7 (to March 2020)
* Citrix Hypervisor (XenServer) 7.1 LTSR, 8.0
* KVM

|*File Systems*
|The following file systems are supported:

* *XFS*
* *ext3* or *ext4* file systems for Linux deployments
// Commenting since Zextras backup does not support NFS. Requested from Nagesh. * *NFS* for backup only

The following file system is not supported for *Store/HSM/Backup* features:

* *NFS*

|*Other Dependencies*
|Netcat (`nc`) is required on all operating systems using {product-name}.
Install the `nc` utility before installation or upgrading.

For SUSE and Ubuntu systems, disable *AppArmor* and verify that the
AppArmor service is not running before installing {product-name}.

For Red Hat Enterprise, Fedora Core and SUSE operating systems, the
server must also have the following installed:

* **NPTL**. Native POSIX Thread Library
* **Sudo**. Superuser, required to delegate admins.
* **libidn**. For internationalizing domain names in applications (IDNA)
* **GMP**. GNU Multiple-Precision Library.

For Ubuntu 16 and 18:

* Sudo
* libidn11
* libpcre3
* libexpat1
* libgmp3c2

|*Miscellaneous*
|* SSH client software to transfer and install the {product-name} software.
* Valid DNS configured with an A record and MX record.
* Servers should be configured to run Network Time Protocol (NTP) on a scheduled basis.

a|*Administrator Computers* +
 +
// HACK because including a NOTE in a narrow table column causes problems for
// the prawn layout engine for PDFs.
NOTE: Other configurations may work.
|The following operating system/browser combinations are supported:

Windows 8.1 or Windows 10 with one of the following:

* Microsoft support is only available for Internet Explorer 11 or Microsoft Edge
** IE11 and higher for Windows 8.1
** IE11 or Microsoft Edge for Windows 10
* The latest stable release of:
** Firefox
** Safari
** Google Chrome

IMPORTANT: IE11 is not supported when using {product-short} Connect. {product-short} Connect requires webRTC support which IE doesn't provide yet. 

MacOS 10.12 or later with one of the following:

* The latest stable release of:
** Firefox
** Safari
** Google Chrome

Linux (Red Hat, Ubuntu, Fedora, or SUSE) with one of the following:

* The latest stable release of:
** Firefox
** Google Chrome

|*Administrator Console Monitor*
|Display minimum resolution 1024 x 768

a|*End User Computers using {product-short} Web Client* +
 +
// HACK because including a NOTE in a narrow table column causes problems for
// the prawn layout engine for PDFs.
NOTE: Other configurations may work.

|*For {product-short} Web Client - Classic & Modern version*

Minimum

* Intel/AMD w/ PassMark CPU Mark > 2,000 (e.g., Intel Core i3-7020U @ 2.30GHz = 2,434)
* 2GB RAM

Recommended

* Intel/AMD w/ PassMark CPU Mark > 4,000
* 4GB RAM

The following operating system/browser combinations are supported:

Windows 8.1 or Windows 10 with the latest stable release of one of the following:

** Google Chrome
** Firefox
** Microsoft Edge

MacOS 10.13 or newer with the latest stable release of one of the following:

** Google Chrome
** Firefox
** Safari

Linux (Red Hat, Ubuntu, Fedora, or SUSE) with the latest stable release of one of the following:

** Google Chrome
** Firefox

a|*Mobile Devices using {product-short} Web Client* +
 +

|{product-short} {product-version} supports mobile web browsers using the *{modern-client} only*. 

The following operating system/browser combinations are supported:

Apple-supported iPhone and iPad models with their latest iOS version and with the latest stable release of one of the following:

** Safari
** Chrome
** Firefox

Phones or tablets running an up-to-date version of Android still supported by Google with the latest stable release of one of the following:

** Android Browser
** Chrome
** Firefox

|*End User Computers Using Other Clients*
|Minimum

* Intel/AMD w/ PassMark CPU Mark > 2,000
* 2G RAM

Recommended

* Intel/AMD w/ PassMark CPU Mark > 4,000
* 4GB RAM

Operating system POP/IMAP combinations

* Windows 10 with Windows Mail, Outlook 2016 and above (MAPI), or the latest stable Thunderbird
* Fedora 31 or later with the latest stable Thunderbird
* MacOS 10.12 or later with Apple Mail

|*Exchange Web Services*
|EWS Clients

* Outlook 2016/2019 (MAC only)
* Apple Desktop Clients (macOS 10.12+)

EWS Interoperability

* Exchange 2010+

|*Monitor*
|Display minimum resolution: 1024 x 768

|*Internet Connection Speed*
|1 mbps or higher
|===

[[Zimbra_Connector_for_Outlook]]
== {product-short} Connector for Outlook

[width="100%",cols="20%,80%",]
|=======================================================================
|*Operating System* a|
* Windows 10

|*Microsoft Outlook* a|
* Outlook 2019: 32-bit and 64-bit editions of Microsoft Office, including Click to run.
* Outlook 2016: 32-bit and 64-bit editions of Microsoft Office, including Office365 and Click to run versions.
* Outlook 2013: 32-bit and 64-bit editions of Microsoft Office.

|=======================================================================

[[Zimbra_Mobile]]
== {product-short} Mobile

Mobile (MobileSync) provides mobile data access to email,
calendar, and contacts for users of selected mobile operating systems,
including:

*Smartphone Operating Systems*:

* iOS versions currently supported by Apple; as of March 2020 those are iOS12 & iOS13
* Android versions currently supported by Google; as of March 2020 those are 8.0 and above
* Windows Mobile no longer supported (EOL 10 December 2019)

[[Available_Languages]]
== Available Languages

This section includes information about available languages, including
<<end_user_translations,End User Translations>> and
<<admin_translations,Administrator Translations>>.

[[end_user_translations]]
=== End User Translations

[cols="15,15,70",]
|=======================================================================
|*Component* |*Category* |*Languages*

|{product-short} {web-client} |Application/UI |Arabic, Basque (EU), Chinese
(Simplified PRC and Traditional HK), Danish, Dutch, English (AU, UK,
US), French, French Canadian, German, Hindi, Hungarian, Italian,
Japanese, Korean, Malay, Polish, Portuguese (Brazil), Portuguese
(Portugal), Romanian, Russian, Spanish, Swedish, Thai, Turkish,
Ukrainian

|{product-short} {modern-client} |Application/UI |Chinese
(China), English (US), French (France), German, 
Hindi, Indonesian, Italian,
Japanese, Portuguese (Portugal), Spanish, Thai 

|{product-short} {web-client} - Online Help (HTML) |Feature Documentation |Dutch,
English, Spanish, French, Italian, Japanese, German, Portuguese
(Brazil), Chinese (Simplified PRC and Traditional HK), Russian

|{product-short} {modern-client} - Online End User Guide (HTML) |Feature Documentation |
English

|{product-short} {web-client} - End User Guide (PDF) |Feature Documentation
|English

|{product-short} Connector for Microsoft Outlook |Installer + Application/UI
|Arabic, Basque (EU), Chinese (Simplified PRC and Traditional HK),
Danish, Dutch, English (AU, UK, US), French, French Canadian, German,
Hindi, Hungarian, Italian, Japanese, Korean, Malay, Polish, Portuguese
(Brazil), Portuguese (Portugal), Romanian, Russian, Spanish, Swedish,
Thai, Turkish, Ukrainian

|{product-short} Connector for Microsoft Outlook - End User Guide (PDF) |Feature
Documentation |English
|=======================================================================

[[admin_translations]]
=== Administrator Translations

[cols="15,15,70",]
|=======================================================================
|*Component* |*Category* |*Languages*
|{product-short} Admin Console |Application |Arabic, Basque (EU), Chinese
(Simplified PRC and Traditional HK), Danish, Dutch, English (AU, UK,
US), French, French Canadian, German, Hindi, Hungarian, Italian,
Japanese, Korean, Malay, Polish, Portuguese (Brazil), Portuguese
(Portugal), Romanian, Russian, Spanish, Swedish, Turkish, Ukrainian

|{product-short} Admin Console Online Help (HTML) |Feature Documentation |English

|"Documentation" Install + Upgrade / Admin Manual / Migration / Import /
Release Notes / System Requirements |Guides |English

|{product-short} Connector for Microsoft Outlook - Admin Guide (PDF) |
Install + Configuration Guide |English
|=======================================================================

Note: To find SSH client software, go to Download.com at
http://www.download.com/, and search for SSH. The list displays software
that can be purchased or downloaded for free. An example of a free SSH
client software is PuTTY, a software implementation of SSH for Win32 and
Unix platforms. To download a copy go to http://putty.nl/[http://putty.nl]
